// AUTO-GENERATED by build:wasm — do not edit. Regenerate with: npm run build:wasm

import { getSharedMemory, setHeapBase } from '../runtime';

const B64 =
  'AGFzbQEAAAABBwFgAn9/AX8CDwEDZW52Bm1lbW9yeQIAEgMEAwAAAAYJAX8BQYCAyAALBzQDDmFsbF9maW5pdGVfZjY0AAAOYWxsX2Zpbml0ZV9mMzIAAQ5hbGxfZmluaXRlX3UxNgACCqAFA7EBAgV/AXsCQAJAAkAgAUF+cSICDQBBACEDDAELIAJBf2pBfnFBAmohA0EAIQQgACEFQQAhBgNAIAX9AAMA/QwAAAAAAADwfwAAAAAAAPB/Igf9TiAH/dYBIgf9HQAgB/0dAYSnQQFxDQIgBUEQaiEFIAZBAmoiBiACSQ0ACwtBASEEIAMgAU8NACAAIANBA3RqKQMAQoCAgICAgID4/wCDQoCAgICAgID4/wBSIQQLIAQL4QECBX8BewJAAkACQCABQXxxIgINAEEAIQMMAQsgAkF/akF8cUEEaiEDQQAhBCAAIQVBACEGA0AgBf0AAgD9DAAAgH8AAIB/AACAfwAAgH8iB/1OIAf9NyIH/RsAIAf9GwFyQQFxDQIgB/0bAkEBcQ0CIAf9GwNBAXENAiAFQRBqIQUgBkEEaiIGIAJJDQALC0EBIQQgASADTQ0AIAEgA2shBiAAIANBAnRqIQUCQANAIAUoAgBBgICA/AdxQYCAgPwHRg0BIAVBBGohBSAGQX9qIgZFDQIMAAsLQQAhBAsgBAuHAgIFfwF7AkACQAJAIAFBeHEiAg0AQQAhAwwBCyACQX9qQXhxQQhqIQNBACEEIAAhBUEAIQYDQCAF/QABAP0MAHwAfAB8AHwAfAB8AHwAfCIH/U4gB/0tIgf9GQAgB/0ZAXJBAXENAiAH/RkCQQFxDQIgB/0ZA0EBcQ0CIAf9GQRBAXENAiAH/RkFQQFxDQIgB/0ZBkEBcQ0CIAf9GQdBAXENAiAFQRBqIQUgBkEIaiIGIAJJDQALCwJAIAEgA0sNAEEBDwsgASADayEGIAAgA0EBdGohBQJAA0AgBS8BAEGA+AFxQYD4AUYNASAFQQJqIQUgBkF/aiIGDQALQQEPC0EAIQQLIAQL';

let inst: WebAssembly.Instance | null = null;

function init(): WebAssembly.Instance {
  if (inst) return inst;
  const raw = atob(B64);
  const bytes = new Uint8Array(raw.length);
  for (let i = 0; i < raw.length; i++) bytes[i] = raw.charCodeAt(i);
  inst = new WebAssembly.Instance(new WebAssembly.Module(bytes), {
    env: { memory: getSharedMemory() },
  });
  // Register heap base so runtime knows where safe allocation starts
  const heapBase = inst.exports['__heap_base'];
  if (heapBase && typeof (heapBase as WebAssembly.Global).value === 'number') {
    setHeapBase((heapBase as WebAssembly.Global).value as number);
  }
  return inst;
}

export function all_finite_f64(a: number, N: number): number {
  const i = init();
  return (i.exports['all_finite_f64'] as (...args: number[]) => number)(a, N);
}

export function all_finite_f32(a: number, N: number): number {
  const i = init();
  return (i.exports['all_finite_f32'] as (...args: number[]) => number)(a, N);
}

export function all_finite_u16(a: number, N: number): number {
  const i = init();
  return (i.exports['all_finite_u16'] as (...args: number[]) => number)(a, N);
}
