// AUTO-GENERATED by build:wasm — do not edit. Regenerate with: npm run build:wasm

import { getSharedMemory, setHeapBase } from '../runtime';

const B64 =
  'AGFzbQEAAAABHAZgAABgAAF/YAJ/fwF/YAF/AX9gAX8AYAJ/fwACDwEDZW52Bm1lbW9yeQIAEwMHBgABAgMEBQQFAXABAQEGCQF/AUGAgckACwdIBQ9oZWFwX2ZyZWVfYnl0ZXMAAQxoZWFwX3JlYWxsb2MAAgtoZWFwX21hbGxvYwADCWhlYXBfZnJlZQAECWhlYXBfaW5pdAAFCAEACssHBg4AQYCACUEAQfwA/AsACy0BAn9BACgCiICJgABBAEEAKAKEgImAACIAQQAoAoCAiYAAayIBIAEgAEsbaguxBAEGfwJAAkAgAA0AAkAgAQ0AQQAPC0EAIQICQEEAQRsgAUF/amdrIAFBIUkbIgBBAnQiAygCjICJgAAiAUUNACADQYyAiYAAaiABKAAENgIAQQBBACgCiICJgABBYCAAdGo2AoiAiYAAIAFBCGoPC0EAKAKAgImAAEEHakF4cSIBQSAgAHRqQQhqIgNBACgChICJgABLDQFBACADNgKAgImAACABIAA2AgAgAUEEckEANgIAIAFBCGoPCyAAQXhqIgQoAAAhAwJAIAENAAJAIANBG00NAEEADwsgAEF8aiADQQJ0IgEoAoyAiYAANgAAIAEgBDYCjICJgABBAEEAKAKIgImAAEEgIAN0ajYCiICJgABBAA8LAkBBAEEbIAFBf2pnayABQSFJGyIFIANHDQAgAA8LAkACQCAFQQJ0IgIoAoyAiYAAIgZFDQAgAkGMgImAAGogBigABDYCAEEAQQAoAoiAiYAAQWAgBXRqNgKIgImAAAwBC0EAIQJBACgCgICJgABBB2pBeHEiBkEgIAV0akEIaiIHQQAoAoSAiYAASw0BQQAgBzYCgICJgAAgBiAFNgIAIAZBBHJBADYCAAsgBkEIaiECAkBBICADdCIDIAEgAyABSRsiAUUNACACIAAgAfwKAAALIAQoAAAiAUEbSw0AIABBfGogAUECdCIAKAKMgImAADYAACAAIAQ2AoyAiYAAQQBBACgCiICJgABBICABdGo2AoiAiYAACyACC7oBAQN/AkACQCAADQBBACEBDAELQQAhAQJAQQBBGyAAQX9qZ2sgAEEhSRsiAkECdCIDKAKMgImAACIARQ0AIANBjICJgABqIAAoAAQ2AgBBAEEAKAKIgImAAEFgIAJ0ajYCiICJgAAgAEEIag8LQQAoAoCAiYAAQQdqQXhxIgBBICACdGpBCGoiA0EAKAKEgImAAEsNAEEAIAM2AoCAiYAAIAAgAjYCACAAQQRyQQA2AgAgAEEIag8LIAELVgECfwJAIABFDQAgAEF4aiIBKAAAIgJBG0sNACAAQXxqIAJBAnQiACgCjICJgAA2AAAgACABNgKMgImAAEEAQQAoAoiAiYAAQSAgAnRqNgKIgImAAAsLRgBBACAAQQdqQXhxNgKAgImAAEEAIAEgAGpBeHE2AoSAiYAAQQBBADYCiICJgAACQEHwAEUNAEGMgImAAEEAQfAA/AsACws=';

let inst: WebAssembly.Instance | null = null;

function init(): WebAssembly.Instance {
  if (inst) return inst;
  const raw = atob(B64);
  const bytes = new Uint8Array(raw.length);
  for (let i = 0; i < raw.length; i++) bytes[i] = raw.charCodeAt(i);
  inst = new WebAssembly.Instance(new WebAssembly.Module(bytes), {
    env: { memory: getSharedMemory() },
  });
  // Register heap base so runtime knows where safe allocation starts
  const heapBase = inst.exports['__heap_base'];
  if (heapBase && typeof (heapBase as WebAssembly.Global).value === 'number') {
    setHeapBase((heapBase as WebAssembly.Global).value as number);
  }
  return inst;
}

export function heap_init(base: number, size: number): void {
  const i = init();
  (i.exports['heap_init'] as (...args: number[]) => void)(base, size);
}

export function heap_malloc(req_size: number): number {
  const i = init();
  return (i.exports['heap_malloc'] as (...args: number[]) => number)(req_size);
}

export function heap_free(ptr: number): void {
  const i = init();
  (i.exports['heap_free'] as (...args: number[]) => void)(ptr);
}

export function heap_realloc(ptr: number, new_size: number): number {
  const i = init();
  return (i.exports['heap_realloc'] as (...args: number[]) => number)(ptr, new_size);
}

export function heap_free_bytes(): number {
  const i = init();
  return (i.exports['heap_free_bytes'] as (...args: number[]) => number)();
}
