// AUTO-GENERATED by build:wasm — do not edit. Regenerate with: npm run build:wasm

import { getSharedMemory, setHeapBase } from '../runtime';

const B64 =
  'AGFzbQEAAAABDAJgA39/fwBgAXwBfAIPAQNlbnYGbWVtb3J5AgAQAwUEAAEAAAYJAX8BQYCAwAALBygDCmFyY2Nvc19mNjQAAAphcmNjb3NfZjMyAAIKYXJjY29zX2k2NAADCrsHBDQAAkAgAkUNAANAIAEgACsDABCBgICAADkDACABQQhqIQEgAEEIaiEAIAJBf2oiAg0ACwsLlgYFAX4BfwF8AXsBfAJAIAC9IgFCIIinQf////8HcSICQYCAwP8DSQ0AAkAgAkGAgMCAfGogAadyRQ0ARAAAAAAAAPh/DwtEAAAAAAAAAABEGC1EVPshCUAgAUJ/VRsPCwJAIAJBgICA/wNJDQACQCABQn9VDQBEGC1EVPsh+T8gAEQAAAAAAADwP6BEAAAAAAAA4D+iIgCfIgMgAyAAIAD9FCIEIAQgBCAE/QwAAAAAAAAAAIKSLrHFuLM/IABECff9DeE9Aj+iRIiyAXXg70k/oP0iAP3yAf0MO49otSiCpL9ZAY0bbAbmv/3wAf3yAf0MVUSIDlXByT/Iilmc5SoAQP3wAf3yAf0MfW/rAxLW1L9LLYocJzoDwP3wAf3yAf0MVVVVVVVVxT8AAAAAAADwP/3wASIE/SEAoiAE/SEBo6JEB1wUMyamkbygoKEiACAAoA8LRAAAAAAAAPA/IAChRAAAAAAAAOA/oiIAIACfIgW9QoCAgIBwg78iAyADoqEgBSADoKMgBSAAIAD9FCIEIAQgBCAE/QwAAAAAAAAAAIKSLrHFuLM/IABECff9DeE9Aj+iRIiyAXXg70k/oP0iAP3yAf0MO49otSiCpL9ZAY0bbAbmv/3wAf3yAf0MVUSIDlXByT/Iilmc5SoAQP3wAf3yAf0MfW/rAxLW1L9LLYocJzoDwP3wAf3yAf0MVVVVVVVVxT8AAAAAAADwP/3wASIE/SEAoiAE/SEBo6KgIAOgIgAgAKAPCwJAIAJBgYCA4wNPDQBEGC1EVPsh+T8PC0QHXBQzJqaRPCAAIAAgAKIiAyAD/RQiBCAEIAQgBP0MAAAAAAAAAACCki6xxbizPyADRAn3/Q3hPQI/okSIsgF14O9JP6D9IgD98gH9DDuPaLUogqS/WQGNG2wG5r/98AH98gH9DFVEiA5Vwck/yIpZnOUqAED98AH98gH9DH1v6wMS1tS/Sy2KHCc6A8D98AH98gH9DFVVVVVVVcU/AAAAAAAA8D/98AEiBP0hAKIgBP0hAaOioSAAoUQYLURU+yH5P6ALNgACQCACRQ0AA0AgASAAKgIAuxCBgICAALY4AgAgAUEEaiEBIABBBGohACACQX9qIgINAAsLCzUAAkAgAkUNAANAIAEgACkDALkQgYCAgAA5AwAgAUEIaiEBIABBCGohACACQX9qIgINAAsLCw==';

let inst: WebAssembly.Instance | null = null;

function init(): WebAssembly.Instance {
  if (inst) return inst;
  const raw = atob(B64);
  const bytes = new Uint8Array(raw.length);
  for (let i = 0; i < raw.length; i++) bytes[i] = raw.charCodeAt(i);
  inst = new WebAssembly.Instance(new WebAssembly.Module(bytes), {
    env: { memory: getSharedMemory() },
  });
  // Register heap base so runtime knows where safe allocation starts
  const heapBase = inst.exports['__heap_base'];
  if (heapBase && typeof (heapBase as WebAssembly.Global).value === 'number') {
    setHeapBase((heapBase as WebAssembly.Global).value as number);
  }
  return inst;
}

export function arccos_f64(a: number, out: number, N: number): void {
  const i = init();
  (i.exports['arccos_f64'] as (...args: number[]) => void)(a, out, N);
}

export function arccos_f32(a: number, out: number, N: number): void {
  const i = init();
  (i.exports['arccos_f32'] as (...args: number[]) => void)(a, out, N);
}

export function arccos_i64(a: number, out: number, N: number): void {
  const i = init();
  (i.exports['arccos_i64'] as (...args: number[]) => void)(a, out, N);
}
