// AUTO-GENERATED by build:wasm — do not edit. Regenerate with: npm run build:wasm

import { getSharedMemory, setHeapBase } from '../runtime';

const B64 =
  'AGFzbQEAAAABDAJgA39/fwBgAXwBfAIPAQNlbnYGbWVtb3J5AgAVAwwLAAEAAAAAAAAAAAAEBQFwAQEBBgkBfwFBgIDSAAsHoQEKDWFyY3Npbl91OF9mMzIAAA1hcmNzaW5faThfZjMyAAIOYXJjc2luX3UxNl9mMzIAAw5hcmNzaW5faTE2X2YzMgAEDmFyY3Npbl91MzJfZjY0AAUOYXJjc2luX2kzMl9mNjQABg5hcmNzaW5fdTY0X2Y2NAAHDmFyY3Npbl9pNjRfZjY0AAgKYXJjc2luX2YzMgAJCmFyY3Npbl9mNjQACgqWCQs2AAJAIAJFDQADQCABIAAtAAC4EIGAgIAAtjgCACABQQRqIQEgAEEBaiEAIAJBf2oiAg0ACwsL8wQEAX4BfwN8AXsCQCAAvSIBQiCIp0H/////B3EiAkGAgMD/A0kNAAJAIAJBgIDAgHxqIAGncg0AIABEGC1EVPsh+T+iRAAAAAAAAHA4oA8LRAAAAAAAAAAAIAAgAKGjDwsCQAJAIAJBgICA/wNJDQBEAAAAAAAA8D8gAJmhRAAAAAAAAOA/oiIAIAAgACAAIAAgAEQJ9/0N4T0CP6JEiLIBdeDvST+gokQ7j2i1KIKkv6CiRFVEiA5Vwck/oKJEfW/rAxLW1L+gokRVVVVVVVXFP6CiIAAgACAAIABEgpIuscW4sz+iRFkBjRtsBua/oKJEyIpZnOUqAECgokRLLYocJzoDwKCiRAAAAAAAAPA/oKMhAyAAnyEEAkAgAkGy5rz/A00NAEQYLURU+yH5PyAEIAQgA6KgIgAgAKBEB1wUMyamkbygoSIAmiAAIAFCAFMbDwtEGC1EVPsh6T8gBL1CgICAgHCDvyIFIAWgoUQHXBQzJqaRPCAAIAUgBaKhIAQgBaCjIgAgAKChIAQgBKAgA6KhoEQYLURU+yHpP6AiAJogACABQgBTGyEADAELIAJBgIBAakGAgIDyA0kNACAAIAAgACAAoiIEIAT9FCIGIAYgBiAG/QwAAAAAAAAAAIKSLrHFuLM/IARECff9DeE9Aj+iRIiyAXXg70k/oP0iAP3yAf0MO49otSiCpL9ZAY0bbAbmv/3wAf3yAf0MVUSIDlXByT/Iilmc5SoAQP3wAf3yAf0MfW/rAxLW1L9LLYocJzoDwP3wAf3yAf0MVVVVVVVVxT8AAAAAAADwP/3wASIG/SEAoiAG/SEBo6KgDwsgAAs2AAJAIAJFDQADQCABIAAsAAC3EIGAgIAAtjgCACABQQRqIQEgAEEBaiEAIAJBf2oiAg0ACwsLNgACQCACRQ0AA0AgASAALwEAuBCBgICAALY4AgAgAUEEaiEBIABBAmohACACQX9qIgINAAsLCzYAAkAgAkUNAANAIAEgAC4BALcQgYCAgAC2OAIAIAFBBGohASAAQQJqIQAgAkF/aiICDQALCws1AAJAIAJFDQADQCABIAAoAgC4EIGAgIAAOQMAIAFBCGohASAAQQRqIQAgAkF/aiICDQALCws1AAJAIAJFDQADQCABIAAoAgC3EIGAgIAAOQMAIAFBCGohASAAQQRqIQAgAkF/aiICDQALCws1AAJAIAJFDQADQCABIAApAwC6EIGAgIAAOQMAIAFBCGohASAAQQhqIQAgAkF/aiICDQALCws1AAJAIAJFDQADQCABIAApAwC5EIGAgIAAOQMAIAFBCGohASAAQQhqIQAgAkF/aiICDQALCws2AAJAIAJFDQADQCABIAAqAgC7EIGAgIAAtjgCACABQQRqIQEgAEEEaiEAIAJBf2oiAg0ACwsLNAACQCACRQ0AA0AgASAAKwMAEIGAgIAAOQMAIAFBCGohASAAQQhqIQAgAkF/aiICDQALCws=';

let inst: WebAssembly.Instance | null = null;

function init(): WebAssembly.Instance {
  if (inst) return inst;
  const raw = atob(B64);
  const bytes = new Uint8Array(raw.length);
  for (let i = 0; i < raw.length; i++) bytes[i] = raw.charCodeAt(i);
  inst = new WebAssembly.Instance(new WebAssembly.Module(bytes), {
    env: { memory: getSharedMemory() },
  });
  // Register heap base so runtime knows where safe allocation starts
  const heapBase = inst.exports['__heap_base'];
  if (heapBase && typeof (heapBase as WebAssembly.Global).value === 'number') {
    setHeapBase((heapBase as WebAssembly.Global).value as number);
  }
  return inst;
}

export function arcsin_f64(a: number, out: number, N: number): void {
  const i = init();
  (i.exports['arcsin_f64'] as (...args: number[]) => void)(a, out, N);
}

export function arcsin_f32(a: number, out: number, N: number): void {
  const i = init();
  (i.exports['arcsin_f32'] as (...args: number[]) => void)(a, out, N);
}

export function arcsin_i64_f64(a: number, out: number, N: number): void {
  const i = init();
  (i.exports['arcsin_i64_f64'] as (...args: number[]) => void)(a, out, N);
}

export function arcsin_u64_f64(a: number, out: number, N: number): void {
  const i = init();
  (i.exports['arcsin_u64_f64'] as (...args: number[]) => void)(a, out, N);
}

export function arcsin_i32_f64(a: number, out: number, N: number): void {
  const i = init();
  (i.exports['arcsin_i32_f64'] as (...args: number[]) => void)(a, out, N);
}

export function arcsin_u32_f64(a: number, out: number, N: number): void {
  const i = init();
  (i.exports['arcsin_u32_f64'] as (...args: number[]) => void)(a, out, N);
}

export function arcsin_i16_f32(a: number, out: number, N: number): void {
  const i = init();
  (i.exports['arcsin_i16_f32'] as (...args: number[]) => void)(a, out, N);
}

export function arcsin_u16_f32(a: number, out: number, N: number): void {
  const i = init();
  (i.exports['arcsin_u16_f32'] as (...args: number[]) => void)(a, out, N);
}

export function arcsin_i8_f32(a: number, out: number, N: number): void {
  const i = init();
  (i.exports['arcsin_i8_f32'] as (...args: number[]) => void)(a, out, N);
}

export function arcsin_u8_f32(a: number, out: number, N: number): void {
  const i = init();
  (i.exports['arcsin_u8_f32'] as (...args: number[]) => void)(a, out, N);
}
