// AUTO-GENERATED by build:wasm — do not edit. Regenerate with: npm run build:wasm

import { getSharedMemory, setHeapBase } from '../runtime';

const B64 =
  'AGFzbQEAAAABDAJgA39/fwBgAXwBfAIPAQNlbnYGbWVtb3J5AgAXAwwLAAEAAAAAAAAAAAAEBQFwAQEBBgkBfwFBwIDYAAsHoQEKDWFyY3Rhbl91OF9mMzIAAA1hcmN0YW5faThfZjMyAAIOYXJjdGFuX3UxNl9mMzIAAw5hcmN0YW5faTE2X2YzMgAEDmFyY3Rhbl91MzJfZjY0AAUOYXJjdGFuX2kzMl9mNjQABg5hcmN0YW5fdTY0X2Y2NAAHDmFyY3Rhbl9pNjRfZjY0AAgKYXJjdGFuX2YzMgAJCmFyY3Rhbl9mNjQACgrtCAs2AAJAIAJFDQADQCABIAAtAAC4EIGAgIAAtjgCACABQQRqIQEgAEEBaiEAIAJBf2oiAg0ACwsLygQEAX8BfgJ/A3wjgICAgABBEGsiASSAgICAAAJAAkAgAL0iAkIgiKdB/////wdxIgNBgIDAoARJDQAgAEQYLURU+yH5P0QYLURU+yH5vyACQn9VGyAAIABiGyEADAELAkACQCADQYCA8P4DSQ0AIACZIQACQCADQYCAzP8DTw0AAkAgA0GAgJj/A08NACAAIACgRAAAAAAAAPC/oCAARAAAAAAAAABAoKMhAEEAIQQMAwsgAEQAAAAAAADwv6AgAEQAAAAAAADwP6CjIQBBASEEDAILAkAgA0GAgI6ABEkNAEQAAAAAAADwvyAAoyEAQQMhBAwCCyAARAAAAAAAAPi/oCAARAAAAAAAAPg/okQAAAAAAADwP6CjIQBBAiEEDAELAkAgA0GAgIDyA0kNAAwBCyADQf//P0sNASABIAC2OAIMIAFBDGohAwwBCyAAIACiIgUgBaIiBiAGIAYgBiAGRC9saixEtKK/okSa/d5SLd6tv6CiRG2adK/ysLO/oKJEcRYj/sZxvL+gokTE65iZmZnJv6CiIQcgBSAGIAYgBiAGIAZEEdoi4zqtkD+iROsNdiRLe6k/oKJEUT3QoGYNsT+gokRuIEzFzUW3P6CiRP+DAJIkScI/oKJEDVVVVVVV1T+goiEGAkAgA0GAgPD+A0kNACAEQQN0IgNBgICYgABqKwMAIAAgByAGoKIgA0GggJiAAGorAwChIAChoSIAIACaIAJCf1UbIQAMAQsgACAAIAcgBqCioSEACyABQRBqJICAgIAAIAALNgACQCACRQ0AA0AgASAALAAAtxCBgICAALY4AgAgAUEEaiEBIABBAWohACACQX9qIgINAAsLCzYAAkAgAkUNAANAIAEgAC8BALgQgYCAgAC2OAIAIAFBBGohASAAQQJqIQAgAkF/aiICDQALCws2AAJAIAJFDQADQCABIAAuAQC3EIGAgIAAtjgCACABQQRqIQEgAEECaiEAIAJBf2oiAg0ACwsLNQACQCACRQ0AA0AgASAAKAIAuBCBgICAADkDACABQQhqIQEgAEEEaiEAIAJBf2oiAg0ACwsLNQACQCACRQ0AA0AgASAAKAIAtxCBgICAADkDACABQQhqIQEgAEEEaiEAIAJBf2oiAg0ACwsLNQACQCACRQ0AA0AgASAAKQMAuhCBgICAADkDACABQQhqIQEgAEEIaiEAIAJBf2oiAg0ACwsLNQACQCACRQ0AA0AgASAAKQMAuRCBgICAADkDACABQQhqIQEgAEEIaiEAIAJBf2oiAg0ACwsLNgACQCACRQ0AA0AgASAAKgIAuxCBgICAALY4AgAgAUEEaiEBIABBBGohACACQX9qIgINAAsLCzQAAkAgAkUNAANAIAEgACsDABCBgICAADkDACABQQhqIQEgAEEIaiEAIAJBf2oiAg0ACwsLC0gBAEGAgBgLQE+7YQVnrN0/GC1EVPsh6T+b9oHSC3PvPxgtRFT7Ifk/4mUvIn8rejwHXBQzJqaBPL3L8HqIB3A8B1wUMyamkTw=';

let inst: WebAssembly.Instance | null = null;

function init(): WebAssembly.Instance {
  if (inst) return inst;
  const raw = atob(B64);
  const bytes = new Uint8Array(raw.length);
  for (let i = 0; i < raw.length; i++) bytes[i] = raw.charCodeAt(i);
  inst = new WebAssembly.Instance(new WebAssembly.Module(bytes), {
    env: { memory: getSharedMemory() },
  });
  // Register heap base so runtime knows where safe allocation starts
  const heapBase = inst.exports['__heap_base'];
  if (heapBase && typeof (heapBase as WebAssembly.Global).value === 'number') {
    setHeapBase((heapBase as WebAssembly.Global).value as number);
  }
  return inst;
}

export function arctan_f64(a: number, out: number, N: number): void {
  const i = init();
  (i.exports['arctan_f64'] as (...args: number[]) => void)(a, out, N);
}

export function arctan_f32(a: number, out: number, N: number): void {
  const i = init();
  (i.exports['arctan_f32'] as (...args: number[]) => void)(a, out, N);
}

export function arctan_i64_f64(a: number, out: number, N: number): void {
  const i = init();
  (i.exports['arctan_i64_f64'] as (...args: number[]) => void)(a, out, N);
}

export function arctan_u64_f64(a: number, out: number, N: number): void {
  const i = init();
  (i.exports['arctan_u64_f64'] as (...args: number[]) => void)(a, out, N);
}

export function arctan_i32_f64(a: number, out: number, N: number): void {
  const i = init();
  (i.exports['arctan_i32_f64'] as (...args: number[]) => void)(a, out, N);
}

export function arctan_u32_f64(a: number, out: number, N: number): void {
  const i = init();
  (i.exports['arctan_u32_f64'] as (...args: number[]) => void)(a, out, N);
}

export function arctan_i16_f32(a: number, out: number, N: number): void {
  const i = init();
  (i.exports['arctan_i16_f32'] as (...args: number[]) => void)(a, out, N);
}

export function arctan_u16_f32(a: number, out: number, N: number): void {
  const i = init();
  (i.exports['arctan_u16_f32'] as (...args: number[]) => void)(a, out, N);
}

export function arctan_i8_f32(a: number, out: number, N: number): void {
  const i = init();
  (i.exports['arctan_i8_f32'] as (...args: number[]) => void)(a, out, N);
}

export function arctan_u8_f32(a: number, out: number, N: number): void {
  const i = init();
  (i.exports['arctan_u8_f32'] as (...args: number[]) => void)(a, out, N);
}
