// AUTO-GENERATED by build:wasm — do not edit. Regenerate with: npm run build:wasm

import { getSharedMemory, setHeapBase } from '../runtime';

const B64 =
  'AGFzbQEAAAABCAFgA39/fwF/Ag8BA2VudgZtZW1vcnkCAB0DBwYAAAAAAAAEBQFwAQEBBgkBfwFBgID0AAsHeAYQYXJnd2hlcmVfZmlsbF9pOAAAEWFyZ3doZXJlX2ZpbGxfaTE2AAERYXJnd2hlcmVfZmlsbF9pMzIAAhFhcmd3aGVyZV9maWxsX2k2NAADEWFyZ3doZXJlX2ZpbGxfZjMyAAQRYXJnd2hlcmVfZmlsbF9mNjQABQrMCQa8AQEEfwJAIAINAEEADwsgAkEBcSEDAkACQCACQQFHDQBBACECQQAhBAwBCyACQX5xIQVBACECQQAhBANAAkAgACACaiIGLQAARQ0AIAEgBEECdGogAjYCACAEQQFqIQQLAkAgBkEBai0AAEUNACABIARBAnRqIAJBAWo2AgAgBEEBaiEECyAFIAJBAmoiAkcNAAsLAkAgA0UNACAAIAJqLQAARQ0AIAEgBEECdGogAjYCACAEQQFqIQQLIAQLxQEBBH8CQCACDQBBAA8LIAJBAXEhAwJAAkAgAkEBRw0AQQAhBEEAIQUMAQsgAkF+cSEGQQAhBCAAIQJBACEFA0ACQCACLwEARQ0AIAEgBUECdGogBDYCACAFQQFqIQULAkAgAkECai8BAEUNACABIAVBAnRqIARBAWo2AgAgBUEBaiEFCyACQQRqIQIgBiAEQQJqIgRHDQALCwJAIANFDQAgACAEQQF0ai8BAEUNACABIAVBAnRqIAQ2AgAgBUEBaiEFCyAFC8UBAQR/AkAgAg0AQQAPCyACQQFxIQMCQAJAIAJBAUcNAEEAIQRBACEFDAELIAJBfnEhBkEAIQQgACECQQAhBQNAAkAgAigCAEUNACABIAVBAnRqIAQ2AgAgBUEBaiEFCwJAIAJBBGooAgBFDQAgASAFQQJ0aiAEQQFqNgIAIAVBAWohBQsgAkEIaiECIAYgBEECaiIERw0ACwsCQCADRQ0AIAAgBEECdGooAgBFDQAgASAFQQJ0aiAENgIAIAVBAWohBQsgBQvFAQEEfwJAIAINAEEADwsgAkEBcSEDAkACQCACQQFHDQBBACEEQQAhBQwBCyACQX5xIQZBACEEIAAhAkEAIQUDQAJAIAIpAwBQDQAgASAFQQJ0aiAENgIAIAVBAWohBQsCQCACQQhqKQMAUA0AIAEgBUECdGogBEEBajYCACAFQQFqIQULIAJBEGohAiAGIARBAmoiBEcNAAsLAkAgA0UNACAAIARBA3RqKQMAUA0AIAEgBUECdGogBDYCACAFQQFqIQULIAUL1AEBBH8CQCACDQBBAA8LIAJBAXEhAwJAAkAgAkEBRw0AQQAhBEEAIQUMAQsgAkF+cSEGQQAhBCAAIQJBACEFA0ACQCACKgIAQwAAAABbDQAgASAFQQJ0aiAENgIAIAVBAWohBQsCQCACQQRqKgIAQwAAAABbDQAgASAFQQJ0aiAEQQFqNgIAIAVBAWohBQsgAkEIaiECIAYgBEECaiIERw0ACwsCQCADRQ0AIAAgBEECdGoqAgBDAAAAAFsNACABIAVBAnRqIAQ2AgAgBUEBaiEFCyAFC+ABAQR/AkAgAg0AQQAPCyACQQFxIQMCQAJAIAJBAUcNAEEAIQRBACEFDAELIAJBfnEhBkEAIQQgACECQQAhBQNAAkAgAisDAEQAAAAAAAAAAGENACABIAVBAnRqIAQ2AgAgBUEBaiEFCwJAIAJBCGorAwBEAAAAAAAAAABhDQAgASAFQQJ0aiAEQQFqNgIAIAVBAWohBQsgAkEQaiECIAYgBEECaiIERw0ACwsCQCADRQ0AIAAgBEEDdGorAwBEAAAAAAAAAABhDQAgASAFQQJ0aiAENgIAIAVBAWohBQsgBQs=';

let inst: WebAssembly.Instance | null = null;

function init(): WebAssembly.Instance {
  if (inst) return inst;
  const raw = atob(B64);
  const bytes = new Uint8Array(raw.length);
  for (let i = 0; i < raw.length; i++) bytes[i] = raw.charCodeAt(i);
  inst = new WebAssembly.Instance(new WebAssembly.Module(bytes), {
    env: { memory: getSharedMemory() },
  });
  // Register heap base so runtime knows where safe allocation starts
  const heapBase = inst.exports['__heap_base'];
  if (heapBase && typeof (heapBase as WebAssembly.Global).value === 'number') {
    setHeapBase((heapBase as WebAssembly.Global).value as number);
  }
  return inst;
}

export function argwhere_fill_f64(a: number, out: number, N: number): number {
  const i = init();
  return (i.exports['argwhere_fill_f64'] as (...args: number[]) => number)(a, out, N);
}

export function argwhere_fill_f32(a: number, out: number, N: number): number {
  const i = init();
  return (i.exports['argwhere_fill_f32'] as (...args: number[]) => number)(a, out, N);
}

export function argwhere_fill_i64(a: number, out: number, N: number): number {
  const i = init();
  return (i.exports['argwhere_fill_i64'] as (...args: number[]) => number)(a, out, N);
}

export function argwhere_fill_i32(a: number, out: number, N: number): number {
  const i = init();
  return (i.exports['argwhere_fill_i32'] as (...args: number[]) => number)(a, out, N);
}

export function argwhere_fill_i16(a: number, out: number, N: number): number {
  const i = init();
  return (i.exports['argwhere_fill_i16'] as (...args: number[]) => number)(a, out, N);
}

export function argwhere_fill_i8(a: number, out: number, N: number): number {
  const i = init();
  return (i.exports['argwhere_fill_i8'] as (...args: number[]) => number)(a, out, N);
}
