// AUTO-GENERATED by build:wasm — do not edit. Regenerate with: npm run build:wasm

import { getSharedMemory, setHeapBase } from '../runtime';

const B64 =
  'AGFzbQEAAAABCgFgBn9/f39/fwACDwEDZW52Bm1lbW9yeQIAIwMHBgAAAAAAAAQFAXABAQEGCQF/AUGAgIwBCwd3CAtjb252b2x2ZV91OAAAC2NvbnZvbHZlX2k4AAEMY29udm9sdmVfdTE2AAIMY29udm9sdmVfaTE2AAIMY29udm9sdmVfdTMyAAMMY29udm9sdmVfaTMyAAMMY29udm9sdmVfZjMyAAQMY29udm9sdmVfZjY0AAUKrQgGmgEBB38CQCADQX9qIgYgAWoiB0UNAEEAIQgDQEEAIQkCQEEAIAggBmsiAyADIAhLGyIDIAhBAWoiCiABIAggAUkbIgtPDQAgAiAIIAYgCCAGSRtqIQxBACEJA0AgDC0AACAAIANqLQAAbCAJaiEJIAxBf2ohDCADQQFqIgMgC0kNAAsLIAQgCGogCToAACAKIQggCiAHRw0ACwsLmgEBB38CQCADQX9qIgYgAWoiB0UNAEEAIQgDQEEAIQkCQEEAIAggBmsiAyADIAhLGyIDIAhBAWoiCiABIAggAUkbIgtPDQAgAiAIIAYgCCAGSRtqIQxBACEJA0AgDC0AACAAIANqLQAAbCAJaiEJIAxBf2ohDCADQQFqIgMgC0kNAAsLIAQgCGogCToAACAKIQggCiAHRw0ACwsLtAEBCH8CQCADQX9qIgYgAWoiB0UNAEEAIQgDQEEAIQkCQEEAIAggBmsiAyADIAhLGyIKIAhBAWoiCyABIAggAUkbIgxPDQAgACAIIAYgCCAGSRtBAXQiDWshAyACIA1qIQ1BACEJA0AgDS8BACADLwEAbCAJaiEJIANBAmohAyANQX5qIQ0gCkEBaiIKIAxJDQALCyAEIAhBAXRqIAk7AQAgAEECaiEAIAshCCALIAdHDQALCwu0AQEIfwJAIANBf2oiBiABaiIHRQ0AQQAhCANAQQAhCQJAQQAgCCAGayIDIAMgCEsbIgogCEEBaiILIAEgCCABSRsiDE8NACAAIAggBiAIIAZJG0ECdCINayEDIAIgDWohDUEAIQkDQCANKAIAIAMoAgBsIAlqIQkgA0EEaiEDIA1BfGohDSAKQQFqIgogDEkNAAsLIAQgCEECdGogCTYCACAAQQRqIQAgCyEIIAsgB0cNAAsLC74BAwN/AX0EfwJAIANBf2oiBiABaiIHRQ0AQQAhCANAQwAAAAAhCQJAQQAgCCAGayIDIAMgCEsbIgogCEEBaiILIAEgCCABSRsiDE8NACAAIAggBiAIIAZJG0ECdCINayEDIAIgDWohDUMAAAAAIQkDQCAJIAMqAgAgDSoCAJSSIQkgA0EEaiEDIA1BfGohDSAKQQFqIgogDEkNAAsLIAQgCEECdGogCTgCACAAQQRqIQAgCyEIIAsgB0cNAAsLC8YBAwN/AXwEfwJAIANBf2oiBiABaiIHRQ0AQQAhCANARAAAAAAAAAAAIQkCQEEAIAggBmsiAyADIAhLGyIKIAhBAWoiCyABIAggAUkbIgxPDQAgACAIIAYgCCAGSRtBA3QiDWshAyACIA1qIQ1EAAAAAAAAAAAhCQNAIAkgAysDACANKwMAoqAhCSADQQhqIQMgDUF4aiENIApBAWoiCiAMSQ0ACwsgBCAIQQN0aiAJOQMAIABBCGohACALIQggCyAHRw0ACwsL';

let inst: WebAssembly.Instance | null = null;

function init(): WebAssembly.Instance {
  if (inst) return inst;
  const raw = atob(B64);
  const bytes = new Uint8Array(raw.length);
  for (let i = 0; i < raw.length; i++) bytes[i] = raw.charCodeAt(i);
  inst = new WebAssembly.Instance(new WebAssembly.Module(bytes), {
    env: { memory: getSharedMemory() },
  });
  // Register heap base so runtime knows where safe allocation starts
  const heapBase = inst.exports['__heap_base'];
  if (heapBase && typeof (heapBase as WebAssembly.Global).value === 'number') {
    setHeapBase((heapBase as WebAssembly.Global).value as number);
  }
  return inst;
}

export function convolve_f64(
  a: number,
  na: number,
  b: number,
  nb: number,
  out: number,
  outLen: number,
): void {
  const i = init();
  (i.exports['convolve_f64'] as (...args: number[]) => void)(a, na, b, nb, out, outLen);
}

export function convolve_f32(
  a: number,
  na: number,
  b: number,
  nb: number,
  out: number,
  outLen: number,
): void {
  const i = init();
  (i.exports['convolve_f32'] as (...args: number[]) => void)(a, na, b, nb, out, outLen);
}

export function convolve_i32(
  a: number,
  na: number,
  b: number,
  nb: number,
  out: number,
  outLen: number,
): void {
  const i = init();
  (i.exports['convolve_i32'] as (...args: number[]) => void)(a, na, b, nb, out, outLen);
}

export function convolve_u32(
  a: number,
  na: number,
  b: number,
  nb: number,
  out: number,
  outLen: number,
): void {
  const i = init();
  (i.exports['convolve_u32'] as (...args: number[]) => void)(a, na, b, nb, out, outLen);
}

export function convolve_i16(
  a: number,
  na: number,
  b: number,
  nb: number,
  out: number,
  outLen: number,
): void {
  const i = init();
  (i.exports['convolve_i16'] as (...args: number[]) => void)(a, na, b, nb, out, outLen);
}

export function convolve_u16(
  a: number,
  na: number,
  b: number,
  nb: number,
  out: number,
  outLen: number,
): void {
  const i = init();
  (i.exports['convolve_u16'] as (...args: number[]) => void)(a, na, b, nb, out, outLen);
}

export function convolve_i8(
  a: number,
  na: number,
  b: number,
  nb: number,
  out: number,
  outLen: number,
): void {
  const i = init();
  (i.exports['convolve_i8'] as (...args: number[]) => void)(a, na, b, nb, out, outLen);
}

export function convolve_u8(
  a: number,
  na: number,
  b: number,
  nb: number,
  out: number,
  outLen: number,
): void {
  const i = init();
  (i.exports['convolve_u8'] as (...args: number[]) => void)(a, na, b, nb, out, outLen);
}
