// AUTO-GENERATED by build:wasm — do not edit. Regenerate with: pnpm run build:wasm

import { getSharedMemory, setHeapBase } from '../runtime';

const B64 =
  'AGFzbQEAAAABCAFgBH9/f38AAg8BA2VudgZtZW1vcnkCAC4DAwIAAAQFAXABAQEGCQF/AUGAgLUBCwcZAglmcmV4cF9mMzIAAAlmcmV4cF9mNjQAAQqmBAL6AQIBfQN/AkAgA0UNAANAAkACQAJAIAAqAgAiBEMAAAAAWw0AIAS8IgVB/////wdxQYCAgPwHSQ0BCyABIAQ4AgBBACEGDAELQQAhBgJAAkAgBUEXdkH/AXEiB0H/AUYNACAHDQEgBUH///8DcUUNACAFQYCAgIB4cSAFIAVBCXRnIgZBAWp0Qf///wNxQQAgBkEfcUEWSRtyQYCAgPgDciEFQYJ/IAZrIQYLIAEgBTYCAAwBCyAHQYJ/aiEGIAEgBUH///+DeHFBgICA+ANyNgIACyACIAY2AgAgAEEEaiEAIAFBBGohASACQQRqIQIgA0F/aiIDDQALCwunAgMBfAF+An8CQCADRQ0AA0ACQAJAAkAgACsDACIERAAAAAAAAAAAYQ0AIAS9IgVC////////////AINCgICAgICAgPj/AFQNAQsgASAEOQMAQQAhBgwBC0EAIQYCQAJAIAVCNIinQf8PcSIHQf8PRg0AIAcNASAFQv////////8Hg1ANACAFQoCAgICAgICAgH+DIAUgBUIMhnmnIgZBAWqthkL/////////B4NCACAGQT9xQTNJG4RCgICAgICAgPA/hCEFQYJ4IAZrIQYLIAEgBTcDAAwBCyAHQYJ4aiEGIAEgBUL/////////h4B/g0KAgICAgICA8D+ENwMACyACIAY2AgAgAEEIaiEAIAFBCGohASACQQRqIQIgA0F/aiIDDQALCws=';

let inst: WebAssembly.Instance | null = null;

function init(): WebAssembly.Instance {
  if (inst) return inst;
  const raw = atob(B64);
  const bytes = new Uint8Array(raw.length);
  for (let i = 0; i < raw.length; i++) bytes[i] = raw.charCodeAt(i);
  inst = new WebAssembly.Instance(new WebAssembly.Module(bytes), {
    env: { memory: getSharedMemory() },
  });
  // Register heap base so runtime knows where safe allocation starts
  const heapBase = inst.exports['__heap_base'];
  if (heapBase && typeof (heapBase as WebAssembly.Global).value === 'number') {
    setHeapBase((heapBase as WebAssembly.Global).value as number);
  }
  return inst;
}

export function frexp_f64(x: number, out_m: number, out_e: number, N: number): void {
  const i = init();
  (i.exports['frexp_f64'] as (...args: number[]) => void)(x, out_m, out_e, N);
}

export function frexp_f32(x: number, out_m: number, out_e: number, N: number): void {
  const i = init();
  (i.exports['frexp_f32'] as (...args: number[]) => void)(x, out_m, out_e, N);
}
