// AUTO-GENERATED by build:wasm — do not edit. Regenerate with: npm run build:wasm

import { getSharedMemory, setHeapBase } from '../runtime';

const B64 =
  'AGFzbQEAAAABCAFgBH9/f38AAg8BA2VudgZtZW1vcnkCADADAwIAAAYJAX8BQYCAwAELBxwCDmdjZF9zY2FsYXJfaTMyAAAHZ2NkX2kzMgABCvsDAvYCAQV/AkAgAkUNAAJAIANFDQAgAyADQR91IgRzIARrIQVBACEGA0AgACAGQQJ0IgdqKAIAIgMgA0EfdSIDcyADayEEIAUhAwNAIAQgAyIIcCEDIAghBCADDQALIAEgB2ogCDYCACAGQQFqIgYgAkcNAAwCCwtBACEGAkAgAkEESQ0AIAEgAGtBEEkNACACQXxxIgYhCCABIQMgACEEA0AgAyAE/QACAP2gAf0LAgAgA0EQaiEDIARBEGohBCAIQXxqIggNAAsgAiAGRg0BCyAGQQFyIQMCQCACQQFxRQ0AIAEgBkECdCIEaiAAIARqKAIAIgQgBEEfdSIEcyAEazYCACADIQYLIAIgA0YNACACIAZrIQggACAGQQJ0IgRqIQMgASAEaiEEA0AgBCADKAIAIgYgBkEfdSIGcyAGazYCACAEQQRqIANBBGooAgAiBiAGQR91IgZzIAZrNgIAIANBCGohAyAEQQhqIQQgCEF+aiIIDQALCwuAAQEFfwJAIANFDQBBACEEA0AgACAEQQJ0IgVqKAIAIgYgBkEfdSIGcyAGayEHAkACQCABIAVqKAIAIgYNACAHIQgMAQsgBiAGQR91IghzIAhrIQYDQCAHIAYiCHAhBiAIIQcgBg0ACwsgAiAFaiAINgIAIARBAWoiBCADRw0ACwsL';

let inst: WebAssembly.Instance | null = null;

function init(): WebAssembly.Instance {
  if (inst) return inst;
  const raw = atob(B64);
  const bytes = new Uint8Array(raw.length);
  for (let i = 0; i < raw.length; i++) bytes[i] = raw.charCodeAt(i);
  inst = new WebAssembly.Instance(new WebAssembly.Module(bytes), {
    env: { memory: getSharedMemory() },
  });
  // Register heap base so runtime knows where safe allocation starts
  const heapBase = inst.exports['__heap_base'];
  if (heapBase && typeof (heapBase as WebAssembly.Global).value === 'number') {
    setHeapBase((heapBase as WebAssembly.Global).value as number);
  }
  return inst;
}

export function gcd_scalar_i32(a: number, out: number, N: number, scalar: number): void {
  const i = init();
  (i.exports['gcd_scalar_i32'] as (...args: number[]) => void)(a, out, N, scalar);
}

export function gcd_i32(a: number, b: number, out: number, N: number): void {
  const i = init();
  (i.exports['gcd_i32'] as (...args: number[]) => void)(a, b, out, N);
}
