// AUTO-GENERATED by build:wasm — do not edit. Regenerate with: npm run build:wasm

import { getSharedMemory, setHeapBase } from '../runtime';

const B64 =
  'AGFzbQEAAAABDgJgBH9/f38AYAN/f38AAg8BA2VudgZtZW1vcnkCADsDBwYAAQABAAEEBQFwAQEBBgkBfwFBgIDsAQsHZwYOaW5kaWNlc18zZF9mNjQAAA5pbmRpY2VzXzJkX2Y2NAABDmluZGljZXNfM2RfaTY0AAIOaW5kaWNlc18yZF9pNjQAAw5pbmRpY2VzXzNkX2kzMgAEDmluZGljZXNfMmRfaTMyAAUK1AkGbQEFfwJAIAMgAmwiBCABbCIFRQ0AIAVBBHQhBiAFQQN0IQdBACEBA0AgACABIARuuDkDACAAIAdqIAEgA24iCCACcLg5AwAgACAGaiABIAggA2xruDkDACAAQQhqIQAgBSABQQFqIgFHDQALCwv/AQEFfwJAIAIgAWwiA0UNACADQQFxIQQCQAJAIANBf2oiBQ0AQQAhAQwBCyADQX5xIQZBACEBIAAhBwNAIAcgASACbrg5AwAgB0EIaiABQQFqIAJuuDkDACAHQRBqIQcgBiABQQJqIgFHDQALCwJAIARFDQAgACABQQN0aiABIAJuuDkDAAsgA0EBcSEEIAAgA0EDdGohAAJAAkAgBQ0AQQAhAQwBCyADQX5xIQZBACEBIAAhBwNAIAcgASACcLg5AwAgB0EIaiABQQFqIAJwuDkDACAHQRBqIQcgBiABQQJqIgFHDQALCyAERQ0AIAAgAUEDdGogASACcLg5AwALC20BBX8CQCADIAJsIgQgAWwiBUUNACAFQQR0IQYgBUEDdCEHQQAhAQNAIAAgASAEbq03AwAgACAHaiABIANuIgggAnCtNwMAIAAgBmogASAIIANsa603AwAgAEEIaiEAIAUgAUEBaiIBRw0ACwsL/wEBBX8CQCACIAFsIgNFDQAgA0EBcSEEAkACQCADQX9qIgUNAEEAIQEMAQsgA0F+cSEGQQAhASAAIQcDQCAHIAEgAm6tNwMAIAdBCGogAUEBaiACbq03AwAgB0EQaiEHIAYgAUECaiIBRw0ACwsCQCAERQ0AIAAgAUEDdGogASACbq03AwALIANBAXEhBCAAIANBA3RqIQACQAJAIAUNAEEAIQEMAQsgA0F+cSEGQQAhASAAIQcDQCAHIAEgAnCtNwMAIAdBCGogAUEBaiACcK03AwAgB0EQaiEHIAYgAUECaiIBRw0ACwsgBEUNACAAIAFBA3RqIAEgAnCtNwMACwtqAQV/AkAgAyACbCIEIAFsIgVFDQAgBUEDdCEGIAVBAnQhB0EAIQEDQCAAIAEgBG42AgAgACAHaiABIANuIgggAnA2AgAgACAGaiABIAggA2xrNgIAIABBBGohACAFIAFBAWoiAUcNAAsLC4gDAQR/AkAgAiABbCIDRQ0AIANBA3EhBEEAIQECQCADQQRJDQBBACADQXxxayEFQQMhASAAIQYDQCAGQQxqIAEgAm42AgAgBkEIaiABQX9qIAJuNgIAIAZBBGogAUF+aiACbjYCACAGIAFBfWogAm42AgAgBkEQaiEGIAUgAUEEaiIBakEDRw0ACyABQX1qIQELAkAgBEUNACAAIAFBAnRqIQYDQCAGIAEgAm42AgAgBkEEaiEGIAFBAWohASAEQX9qIgQNAAsLIANBA3EhBEEAIQECQCADQQRJDQAgACADQQJ0aiEGQQAgA0F8cWshBUEDIQEDQCAGQQxqIAEgAnA2AgAgBkEIaiABQX9qIAJwNgIAIAZBBGogAUF+aiACcDYCACAGIAFBfWogAnA2AgAgBkEQaiEGIAUgAUEEaiIBakEDRw0ACyABQX1qIQELIARFDQAgACADQQJ0IAFBAnRqaiEGA0AgBiABIAJwNgIAIAZBBGohBiABQQFqIQEgBEF/aiIEDQALCws=';

let inst: WebAssembly.Instance | null = null;

function init(): WebAssembly.Instance {
  if (inst) return inst;
  const raw = atob(B64);
  const bytes = new Uint8Array(raw.length);
  for (let i = 0; i < raw.length; i++) bytes[i] = raw.charCodeAt(i);
  inst = new WebAssembly.Instance(new WebAssembly.Module(bytes), {
    env: { memory: getSharedMemory() },
  });
  // Register heap base so runtime knows where safe allocation starts
  const heapBase = inst.exports['__heap_base'];
  if (heapBase && typeof (heapBase as WebAssembly.Global).value === 'number') {
    setHeapBase((heapBase as WebAssembly.Global).value as number);
  }
  return inst;
}

export function indices_2d_i32(out: number, d0: number, d1: number): void {
  const i = init();
  (i.exports['indices_2d_i32'] as (...args: number[]) => void)(out, d0, d1);
}

export function indices_3d_i32(out: number, d0: number, d1: number, d2: number): void {
  const i = init();
  (i.exports['indices_3d_i32'] as (...args: number[]) => void)(out, d0, d1, d2);
}

export function indices_2d_i64(out: number, d0: number, d1: number): void {
  const i = init();
  (i.exports['indices_2d_i64'] as (...args: number[]) => void)(out, d0, d1);
}

export function indices_3d_i64(out: number, d0: number, d1: number, d2: number): void {
  const i = init();
  (i.exports['indices_3d_i64'] as (...args: number[]) => void)(out, d0, d1, d2);
}

export function indices_2d_f64(out: number, d0: number, d1: number): void {
  const i = init();
  (i.exports['indices_2d_f64'] as (...args: number[]) => void)(out, d0, d1);
}

export function indices_3d_f64(out: number, d0: number, d1: number, d2: number): void {
  const i = init();
  (i.exports['indices_3d_f64'] as (...args: number[]) => void)(out, d0, d1, d2);
}
