// AUTO-GENERATED by build:wasm — do not edit. Regenerate with: npm run build:wasm

import { getSharedMemory, setHeapBase } from '../runtime';

const B64 =
  'AGFzbQEAAAABDgJgA39/fwBgBH9/f38AAg8BA2VudgZtZW1vcnkCADUDAwIAAQYJAX8BQYCA1AELBxsCCmluZGljZXNfMmQAAAppbmRpY2VzXzNkAAEKsQQCwwMDAX8CewN/AkAgAiABbCIDRQ0AQQAhAQJAAkAgA0EESQ0AIAL9ESEE/QwAAAAAAQAAAAIAAAADAAAAIQUgA0F8cSIBIQYgACEHA0AgByAF/RsAIAT9GwBu/REgBf0bASAE/RsBbv0cASAF/RsCIAT9GwJu/RwCIAX9GwMgBP0bA279HAP9CwIAIAdBEGohByAF/QwEAAAABAAAAAQAAAAEAAAA/a4BIQUgBkF8aiIGDQALIAMgAUYNAQsgACABQQJ0aiEHA0AgByABIAJuNgIAIAdBBGohByADIAFBAWoiAUcNAAsLIANBAnQhCEEAIQECQCADQQRJDQAgACAIaiEHIAL9ESEE/QwAAAAAAQAAAAIAAAADAAAAIQUgA0F8cSIBIQYDQCAHIAX9GwAgBP0bAHD9ESAF/RsBIAT9GwFw/RwBIAX9GwIgBP0bAnD9HAIgBf0bAyAE/RsDcP0cA/0LAgAgB0EQaiEHIAX9DAQAAAAEAAAABAAAAAQAAAD9rgEhBSAGQXxqIgYNAAsgAyABRg0BCyAAIAggAUECdGpqIQcDQCAHIAEgAnA2AgAgB0EEaiEHIAMgAUEBaiIBRw0ACwsLagEFfwJAIAMgAmwiBCABbCIFRQ0AIAVBA3QhBiAFQQJ0IQdBACEBA0AgACABIARuNgIAIAAgB2ogASADbiIIIAJwNgIAIAAgBmogASAIIANsazYCACAAQQRqIQAgBSABQQFqIgFHDQALCws=';

let inst: WebAssembly.Instance | null = null;

function init(): WebAssembly.Instance {
  if (inst) return inst;
  const raw = atob(B64);
  const bytes = new Uint8Array(raw.length);
  for (let i = 0; i < raw.length; i++) bytes[i] = raw.charCodeAt(i);
  inst = new WebAssembly.Instance(new WebAssembly.Module(bytes), {
    env: { memory: getSharedMemory() },
  });
  // Register heap base so runtime knows where safe allocation starts
  const heapBase = inst.exports['__heap_base'];
  if (heapBase && typeof (heapBase as WebAssembly.Global).value === 'number') {
    setHeapBase((heapBase as WebAssembly.Global).value as number);
  }
  return inst;
}

export function indices_2d(out: number, d0: number, d1: number): void {
  const i = init();
  (i.exports['indices_2d'] as (...args: number[]) => void)(out, d0, d1);
}

export function indices_3d(out: number, d0: number, d1: number, d2: number): void {
  const i = init();
  (i.exports['indices_3d'] as (...args: number[]) => void)(out, d0, d1, d2);
}
