// AUTO-GENERATED by build:wasm — do not edit. Regenerate with: pnpm run build:wasm

import { getSharedMemory, setHeapBase } from '../runtime';

const B64 =
  'AGFzbQEAAAABBwFgA39/fwACDwEDZW52Bm1lbW9yeQIANwMEAwAAAAQFAXABAQEGCQF/AUGAgNwBCwclAwlpc25hbl91MTYAAAlpc25hbl9mMzIAAQlpc25hbl9mNjQAAgq6CgOQAwIEfwF7QQAhAwJAIAJBeHEiBEUNACAAIQUDQCABIANqIgZBB2ogBf0AAAD9DP9//3//f/9//3//f/9//3/9Tv0MAHwAfAB8AHwAfAB8AHwAfP0yIAf9DQACBAYICgwOAAAAAAAAAAD9DAEBAQEBAQEBAQEBAQEBAQH9TiIH/VgAAAcgBkEGaiAH/VgAAAYgBkEFaiAH/VgAAAUgBkEEaiAH/VgAAAQgBkEDaiAH/VgAAAMgBkECaiAH/VgAAAIgBkEBaiAH/VgAAAEgBiAH/VgAAAAgBUEQaiEFIANBCGoiAyAESQ0ACwsCQCACIANNDQAgA0EBaiEGAkAgAiADa0EBcUUNACABIANqIAAgA0EBdGovAQBB//8BcUGA+AFLOgAAIAYhAwsgAiAGRg0AIAEgA2ohBiACIANrIQUgACADQQF0aiEDA0AgBiADLwEAQf//AXFBgPgBSzoAACAGQQFqIANBAmovAQBB//8BcUGA+AFLOgAAIAZBAmohBiADQQRqIQMgBUF+aiIFDQALCwv1AgMEfwF7AX1BACEDAkAgAkF8cSIERQ0AIAAhBQNAIAEgA2oiBkEDaiAF/QACACIHIAf9QiAH/Q0ABAgMAAAAAAAAAAAAAAAA/QwBAQEBAQEBAQEBAQEBAQEB/U4iB/1YAAADIAZBAmogB/1YAAACIAZBAWogB/1YAAABIAYgB/1YAAAAIAVBEGohBSADQQRqIgMgBEkNAAsLAkAgAyACTw0AIAMhBQJAIAIgA2tBA3EiBEUNACAAIANBAnRqIQYgAyEFA0AgASAFaiAGKgIAIgggCFw6AAAgBkEEaiEGIAVBAWohBSAEQX9qIgQNAAsLIAMgAmtBfEsNACAAIAVBAnRqIQYDQCABIAVqIgMgBioCACIIIAhcOgAAIANBAWogBkEEaioCACIIIAhcOgAAIANBAmogBkEIaioCACIIIAhcOgAAIANBA2ogBkEMaioCACIIIAhcOgAAIAFBBGohASAGQRBqIQYgBSACQXxqIgJHDQALCwuuBAMFfwJ7AXwCQAJAIAJBfnEiAw0AQQAhBAwBCwJAAkAgA0F/aiIFQQFHDQBBACEEDAELIAVBAXZBAWpBfnEhBkEAIQQgACEDA0AgASAEaiIHQQFqIAP9AAMAIgggCP1IIAj9DQAIAAAAAAAAAAAAAAAAAAD9DAEBAQEBAQEBAQEBAQEBAQEiCP1OIgn9WAAAASAHIAn9WAAAACAHQQNqIANBEGr9AAMAIgkgCf1IIAj9DQAIAAAAAAAAAAAAAAAAAAAgCP1OIgj9WAAAASAHQQJqIAj9WAAAACADQSBqIQMgBEEEaiEEIAZBfmoiBg0ACwsgBUECcQ0AIAEgBGoiAyAAIARBA3Rq/QADACIIIAj9SCAI/Q0ACAAAAAAAAAAAAAAAAAAA/QwBAQEBAQEBAQEBAQEBAQEB/U4iCP1YAAEBIAMgCP1YAAAAIARBAmohBAsCQCAEIAJPDQAgBCEHAkAgAiAEa0EDcSIGRQ0AIAAgBEEDdGohAyAEIQcDQCABIAdqIAMrAwAiCiAKYjoAACADQQhqIQMgB0EBaiEHIAZBf2oiBg0ACwsgBCACa0F8Sw0AIAAgB0EDdGohAwNAIAEgB2oiBCADKwMAIgogCmI6AAAgBEEBaiADQQhqKwMAIgogCmI6AAAgBEECaiADQRBqKwMAIgogCmI6AAAgBEEDaiADQRhqKwMAIgogCmI6AAAgAUEEaiEBIANBIGohAyAHIAJBfGoiAkcNAAsLCw==';

let inst: WebAssembly.Instance | null = null;

function init(): WebAssembly.Instance {
  if (inst) return inst;
  const raw = atob(B64);
  const bytes = new Uint8Array(raw.length);
  for (let i = 0; i < raw.length; i++) bytes[i] = raw.charCodeAt(i);
  inst = new WebAssembly.Instance(new WebAssembly.Module(bytes), {
    env: { memory: getSharedMemory() },
  });
  // Register heap base so runtime knows where safe allocation starts
  const heapBase = inst.exports['__heap_base'];
  if (heapBase && typeof (heapBase as WebAssembly.Global).value === 'number') {
    setHeapBase((heapBase as WebAssembly.Global).value as number);
  }
  return inst;
}

export function isnan_f64(a: number, out: number, N: number): void {
  const i = init();
  (i.exports['isnan_f64'] as (...args: number[]) => void)(a, out, N);
}

export function isnan_f32(a: number, out: number, N: number): void {
  const i = init();
  (i.exports['isnan_f32'] as (...args: number[]) => void)(a, out, N);
}

export function isnan_u16(a: number, out: number, N: number): void {
  const i = init();
  (i.exports['isnan_u16'] as (...args: number[]) => void)(a, out, N);
}
