// AUTO-GENERATED by build:wasm — do not edit. Regenerate with: npm run build:wasm

import { getSharedMemory, setHeapBase } from '../runtime';

const B64 =
  'AGFzbQEAAAABBwFgA39/fwACDwEDZW52Bm1lbW9yeQIANAMEAwAAAAQFAXABAQEGCQF/AUGAgNABCwclAwlpc25hbl91MTYAAAlpc25hbl9mMzIAAQlpc25hbl9mNjQAAgqoBwOIAwIEfwF7QQAhAwJAIAJBeHEiBEUNACAAIQUDQCABIANqIgZBB2ogBf0AAAD9DP9//3//f/9//3//f/9//3/9Tv0MAHwAfAB8AHwAfAB8AHwAfP0yIgf9GQdBAXE6AAAgBkEGaiAH/RkGQQFxOgAAIAZBBWogB/0ZBUEBcToAACAGQQRqIAf9GQRBAXE6AAAgBkEDaiAH/RkDQQFxOgAAIAZBAmogB/0ZAkEBcToAACAGQQFqIAf9GQFBAXE6AAAgBiAH/RkAQQFxOgAAIAVBEGohBSADQQhqIgMgBEkNAAsLAkAgAiADTQ0AIANBAWohBgJAIAIgA2tBAXFFDQAgASADaiAAIANBAXRqLwEAQf//AXFBgPgBSzoAACAGIQMLIAIgBkYNACABIANqIQYgAiADayEFIAAgA0EBdGohAwNAIAYgAy8BAEH//wFxQYD4AUs6AAAgBkEBaiADQQJqLwEAQf//AXFBgPgBSzoAACAGQQJqIQYgA0EEaiEDIAVBfmoiBQ0ACwsL1AICBH8Be0EAIQMCQCACQXxxIgRFDQAgACEFA0AgASADaiIGQQNqIAX9AAIA/Qz///9/////f////3////9//U79DAAAgH8AAIB/AACAfwAAgH/9PCIH/RsDQQFxOgAAIAZBAmogB/0bAkEBcToAACAGQQFqIAf9GwFBAXE6AAAgBiAH/RsAQQFxOgAAIAVBEGohBSADQQRqIgMgBEkNAAsLAkAgAiADTQ0AIANBAWohBgJAIAIgA2tBAXFFDQAgASADaiAAIANBAnRqKAIAQf////8HcUGAgID8B0s6AAAgBiEDCyACIAZGDQAgASADaiEGIAIgA2shBSAAIANBAnRqIQMDQCAGIAMoAgBB/////wdxQYCAgPwHSzoAACAGQQFqIANBBGooAgBB/////wdxQYCAgPwHSzoAACAGQQJqIQYgA0EIaiEDIAVBfmoiBQ0ACwsLxQEBBH8CQCACRQ0AIAJBAXEhA0EAIQQCQCACQQFGDQAgAkF+cSEFQQAhBCAAIQIDQCABIARqIgYgAikDAEL///////////8Ag0KAgICAgICA+P8AVjoAACAGQQFqIAJBCGopAwBC////////////AINCgICAgICAgPj/AFY6AAAgAkEQaiECIAUgBEECaiIERw0ACwsgA0UNACABIARqIAAgBEEDdGopAwBC////////////AINCgICAgICAgPj/AFY6AAALCw==';

let inst: WebAssembly.Instance | null = null;

function init(): WebAssembly.Instance {
  if (inst) return inst;
  const raw = atob(B64);
  const bytes = new Uint8Array(raw.length);
  for (let i = 0; i < raw.length; i++) bytes[i] = raw.charCodeAt(i);
  inst = new WebAssembly.Instance(new WebAssembly.Module(bytes), {
    env: { memory: getSharedMemory() },
  });
  // Register heap base so runtime knows where safe allocation starts
  const heapBase = inst.exports['__heap_base'];
  if (heapBase && typeof (heapBase as WebAssembly.Global).value === 'number') {
    setHeapBase((heapBase as WebAssembly.Global).value as number);
  }
  return inst;
}

export function isnan_f64(a: number, out: number, N: number): void {
  const i = init();
  (i.exports['isnan_f64'] as (...args: number[]) => void)(a, out, N);
}

export function isnan_f32(a: number, out: number, N: number): void {
  const i = init();
  (i.exports['isnan_f32'] as (...args: number[]) => void)(a, out, N);
}

export function isnan_u16(a: number, out: number, N: number): void {
  const i = init();
  (i.exports['isnan_u16'] as (...args: number[]) => void)(a, out, N);
}
