// AUTO-GENERATED by build:wasm — do not edit. Regenerate with: npm run build:wasm

import { getSharedMemory, setHeapBase } from '../runtime';

const B64 =
  'AGFzbQEAAAABDQJgAn9/AXxgAn9/AX0CDwEDZW52Bm1lbW9yeQIAXAMDAgABBgkBfwFBgIDwAgsHKQIRcmVkdWNlX25hbnN1bV9mNjQAABFyZWR1Y2VfbmFuc3VtX2YzMgABCvUDAv4BBAJ/AXwBfwF8AkAgAQ0ARAAAAAAAAAAADwsgAUEDcSECAkACQCABQQRPDQBBACEDRAAAAAAAAAAAIQQMAQsgAUF8cSEFQQAhA0QAAAAAAAAAACEEIAAhAQNAIAQgASsDACIGoCAEIAYgBmEbIgYgAUEIaisDACIEoCAGIAQgBGEbIgYgAUEQaisDACIEoCAGIAQgBGEbIgYgAUEYaisDACIEoCAGIAQgBGEbIQQgAUEgaiEBIAUgA0EEaiIDRw0ACwsCQCACRQ0AIAAgA0EDdGohAQNAIAQgASsDACIGoCAEIAYgBmEbIQQgAUEIaiEBIAJBf2oiAg0ACwsgBAvyAQQCfwF9AX8BfQJAIAENAEMAAAAADwsgAUEDcSECAkACQCABQQRPDQBBACEDQwAAAAAhBAwBCyABQXxxIQVBACEDQwAAAAAhBCAAIQEDQCAEIAEqAgAiBpIgBCAGIAZbGyIGIAFBBGoqAgAiBJIgBiAEIARbGyIGIAFBCGoqAgAiBJIgBiAEIARbGyIGIAFBDGoqAgAiBJIgBiAEIARbGyEEIAFBEGohASAFIANBBGoiA0cNAAsLAkAgAkUNACAAIANBAnRqIQEDQCAEIAEqAgAiBpIgBCAGIAZbGyEEIAFBBGohASACQX9qIgINAAsLIAQL';

let inst: WebAssembly.Instance | null = null;

function init(): WebAssembly.Instance {
  if (inst) return inst;
  const raw = atob(B64);
  const bytes = new Uint8Array(raw.length);
  for (let i = 0; i < raw.length; i++) bytes[i] = raw.charCodeAt(i);
  inst = new WebAssembly.Instance(new WebAssembly.Module(bytes), {
    env: { memory: getSharedMemory() },
  });
  // Register heap base so runtime knows where safe allocation starts
  const heapBase = inst.exports['__heap_base'];
  if (heapBase && typeof (heapBase as WebAssembly.Global).value === 'number') {
    setHeapBase((heapBase as WebAssembly.Global).value as number);
  }
  return inst;
}

export function reduce_nansum_f64(a: number, N: number): number {
  const i = init();
  return (i.exports['reduce_nansum_f64'] as (...args: number[]) => number)(a, N);
}

export function reduce_nansum_f32(a: number, N: number): number {
  const i = init();
  return (i.exports['reduce_nansum_f32'] as (...args: number[]) => number)(a, N);
}
