// AUTO-GENERATED by build:wasm — do not edit. Regenerate with: npm run build:wasm

import { getSharedMemory, setHeapBase } from '../runtime';

const B64 =
  'AGFzbQEAAAABBwFgAn9/AX8CDwEDZW52Bm1lbW9yeQIATwMHBgAAAAAAAAYJAX8BQYCAvAILB2YGDnJlZHVjZV9hbnlfZjY0AAAOcmVkdWNlX2FueV9mMzIAAQ5yZWR1Y2VfYW55X2k2NAACDnJlZHVjZV9hbnlfaTMyAAMOcmVkdWNlX2FueV9pMTYABA1yZWR1Y2VfYW55X2k4AAUK3QIGQAEBf0EAIQICQCABRQ0AAkADQCAAKwMARAAAAAAAAAAAYg0BIABBCGohACABQX9qIgFFDQIMAAsLQQEhAgsgAgs8AQF/QQAhAgJAIAFFDQACQANAIAAqAgBDAAAAAFwNASAAQQRqIQAgAUF/aiIBRQ0CDAALC0EBIQILIAILOAEBf0EAIQICQCABRQ0AAkADQCAAKQMAUEUNASAAQQhqIQAgAUF/aiIBRQ0CDAALC0EBIQILIAILNgEBf0EAIQICQCABRQ0AAkADQCAAKAIADQEgAEEEaiEAIAFBf2oiAUUNAgwACwtBASECCyACCzYBAX9BACECAkAgAUUNAAJAA0AgAC8BAA0BIABBAmohACABQX9qIgFFDQIMAAsLQQEhAgsgAgs2AQF/QQAhAgJAIAFFDQACQANAIAAtAAANASAAQQFqIQAgAUF/aiIBRQ0CDAALC0EBIQILIAIL';

let inst: WebAssembly.Instance | null = null;

function init(): WebAssembly.Instance {
  if (inst) return inst;
  const raw = atob(B64);
  const bytes = new Uint8Array(raw.length);
  for (let i = 0; i < raw.length; i++) bytes[i] = raw.charCodeAt(i);
  inst = new WebAssembly.Instance(new WebAssembly.Module(bytes), {
    env: { memory: getSharedMemory() },
  });
  // Register heap base so runtime knows where safe allocation starts
  const heapBase = inst.exports['__heap_base'];
  if (heapBase && typeof (heapBase as WebAssembly.Global).value === 'number') {
    setHeapBase((heapBase as WebAssembly.Global).value as number);
  }
  return inst;
}

export function reduce_any_f64(a: number, N: number): number {
  const i = init();
  return (i.exports['reduce_any_f64'] as (...args: number[]) => number)(a, N);
}

export function reduce_any_f32(a: number, N: number): number {
  const i = init();
  return (i.exports['reduce_any_f32'] as (...args: number[]) => number)(a, N);
}

export function reduce_any_i64(a: number, N: number): number {
  const i = init();
  return (i.exports['reduce_any_i64'] as (...args: number[]) => number)(a, N);
}

export function reduce_any_i32(a: number, N: number): number {
  const i = init();
  return (i.exports['reduce_any_i32'] as (...args: number[]) => number)(a, N);
}

export function reduce_any_i16(a: number, N: number): number {
  const i = init();
  return (i.exports['reduce_any_i16'] as (...args: number[]) => number)(a, N);
}

export function reduce_any_i8(a: number, N: number): number {
  const i = init();
  return (i.exports['reduce_any_i8'] as (...args: number[]) => number)(a, N);
}
