// AUTO-GENERATED by build:wasm — do not edit. Regenerate with: npm run build:wasm

import { getSharedMemory, setHeapBase } from '../runtime';

const B64 =
  'AGFzbQEAAAABDQJgAn9/AXxgAn9/AX0CDwEDZW52Bm1lbW9yeQIAVgMDAgABBgkBfwFBgIDYAgsHKQIRcmVkdWNlX25hbm1heF9mNjQAABFyZWR1Y2VfbmFubWF4X2YzMgABCtkIApsEBQF8AX8BewR/BHwCQAJAIAENAEQAAAAAAADw/yECDAELAkACQCABQX5xIgMNAP0MAAAAAAAA8P8AAAAAAADw/yEEQQAhBQwBCyADQX9qIgZBAXZBAWoiB0EDcSEIAkACQCADQQdPDQBBACEH/QwAAAAAAADw/wAAAAAAAPD/IQQMAQsgB0F8cSEFQQAhB/0MAAAAAAAA8P8AAAAAAADw/yEEIAAhAwNAIAQgA/0AAwD99wEgA0EQav0AAwD99wEgA0Egav0AAwD99wEgA0Ewav0AAwD99wEhBCADQcAAaiEDIAdBCGohByAFQXxqIgUNAAsLIAZBfnEhBQJAIAhFDQAgACAHQQN0aiEDA0AgBCAD/QADAP33ASEEIANBEGohAyAIQX9qIggNAAsLIAVBAmohBQsgBP0hACICIAT9IQEiCSACIAlkGyECIAUgAU8NAAJAAkAgASAFa0EDcSIHDQAgBSEIDAELIAAgBUEDdGohAyAFIQgDQCADKwMAIgkgAiAJIAJkGyECIANBCGohAyAIQQFqIQggB0F/aiIHDQALCyAFIAFrQXxLDQAgASAIayEHIAAgCEEDdGohAwNAIANBGGorAwAiCSADQRBqKwMAIgogA0EIaisDACILIAMrAwAiDCACIAwgAmQbIgIgCyACZBsiAiAKIAJkGyICIAkgAmQbIQIgA0EgaiEDIAdBfGoiBw0ACwsgAgu5BAUBfQF/AXsEfwR9AkACQCABDQBDAACA/yECDAELAkACQCABQXxxIgMNAP0MAACA/wAAgP8AAID/AACA/yEEQQAhBQwBCyADQX9qIgZBAnZBAWoiB0EDcSEIAkACQCADQQ1PDQBBACEH/QwAAID/AACA/wAAgP8AAID/IQQMAQsgB0H8////B3EhBUEAIQf9DAAAgP8AAID/AACA/wAAgP8hBCAAIQMDQCAEIAP9AAIA/esBIANBEGr9AAIA/esBIANBIGr9AAIA/esBIANBMGr9AAIA/esBIQQgA0HAAGohAyAHQRBqIQcgBUF8aiIFDQALCyAGQXxxIQUCQCAIRQ0AIAAgB0ECdGohAwNAIAQgA/0AAgD96wEhBCADQRBqIQMgCEF/aiIIDQALCyAFQQRqIQULIAT9HwMiAiAE/R8CIgkgBP0fASIKIAT9HwAiCyAKIAteGyIKIAkgCl4bIgkgAiAJXhshAiAFIAFPDQACQAJAIAEgBWtBA3EiBw0AIAUhCAwBCyAAIAVBAnRqIQMgBSEIA0AgAyoCACIJIAIgCSACXhshAiADQQRqIQMgCEEBaiEIIAdBf2oiBw0ACwsgBSABa0F8Sw0AIAEgCGshByAAIAhBAnRqIQMDQCADQQxqKgIAIgkgA0EIaioCACIKIANBBGoqAgAiCyADKgIAIgwgAiAMIAJeGyICIAsgAl4bIgIgCiACXhsiAiAJIAJeGyECIANBEGohAyAHQXxqIgcNAAsLIAIL';

let inst: WebAssembly.Instance | null = null;

function init(): WebAssembly.Instance {
  if (inst) return inst;
  const raw = atob(B64);
  const bytes = new Uint8Array(raw.length);
  for (let i = 0; i < raw.length; i++) bytes[i] = raw.charCodeAt(i);
  inst = new WebAssembly.Instance(new WebAssembly.Module(bytes), {
    env: { memory: getSharedMemory() },
  });
  // Register heap base so runtime knows where safe allocation starts
  const heapBase = inst.exports['__heap_base'];
  if (heapBase && typeof (heapBase as WebAssembly.Global).value === 'number') {
    setHeapBase((heapBase as WebAssembly.Global).value as number);
  }
  return inst;
}

export function reduce_nanmax_f64(a: number, N: number): number {
  const i = init();
  return (i.exports['reduce_nanmax_f64'] as (...args: number[]) => number)(a, N);
}

export function reduce_nanmax_f32(a: number, N: number): number {
  const i = init();
  return (i.exports['reduce_nanmax_f32'] as (...args: number[]) => number)(a, N);
}
