// AUTO-GENERATED by build:wasm — do not edit. Regenerate with: npm run build:wasm

import { getSharedMemory, setHeapBase } from '../runtime';

const B64 =
  'AGFzbQEAAAABCAFgBH9/f38AAg8BA2VudgZtZW1vcnkCABADBwYAAAAAAAAGCQF/AUGAgMAACwdOBgpyZXBlYXRfZjY0AAAKcmVwZWF0X2YzMgABCnJlcGVhdF9pNjQAAgpyZXBlYXRfaTMyAAMKcmVwZWF0X2kxNgAECXJlcGVhdF9pOAAFCt4JBsIBBQR/AXwBfwF7AX8CQCACRQ0AIANFDQAgA0EDdCEEIANBfnEhBUEAIQYgA0ECSSEHA0AgACAGQQN0aisDACEIQQAhCQJAAkAgBw0AIAj9FCEKIAUhCyABIQkDQCAJIAr9CwMAIAlBEGohCSALQX5qIgsNAAsgBSEJIAMgBUYNAQsgAyAJayELIAEgCUEDdGohCQNAIAkgCDkDACAJQQhqIQkgC0F/aiILDQALCyABIARqIQEgBkEBaiIGIAJHDQALCwvCAQUEfwF9AX8BewF/AkAgAkUNACADRQ0AIANBAnQhBCADQXxxIQVBACEGIANBBEkhBwNAIAAgBkECdGoqAgAhCEEAIQkCQAJAIAcNACAI/RMhCiAFIQsgASEJA0AgCSAK/QsCACAJQRBqIQkgC0F8aiILDQALIAUhCSADIAVGDQELIAMgCWshCyABIAlBAnRqIQkDQCAJIAg4AgAgCUEEaiEJIAtBf2oiCw0ACwsgASAEaiEBIAZBAWoiBiACRw0ACwsLwgEFBH8BfgF/AXsBfwJAIAJFDQAgA0UNACADQQN0IQQgA0F+cSEFQQAhBiADQQJJIQcDQCAAIAZBA3RqKQMAIQhBACEJAkACQCAHDQAgCP0SIQogBSELIAEhCQNAIAkgCv0LAwAgCUEQaiEJIAtBfmoiCw0ACyAFIQkgAyAFRg0BCyADIAlrIQsgASAJQQN0aiEJA0AgCSAINwMAIAlBCGohCSALQX9qIgsNAAsLIAEgBGohASAGQQFqIgYgAkcNAAsLC74BAwZ/AXsBfwJAIAJFDQAgA0UNACADQQJ0IQQgA0F8cSEFQQAhBiADQQRJIQcDQCAAIAZBAnRqKAIAIQhBACEJAkACQCAHDQAgCP0RIQogBSELIAEhCQNAIAkgCv0LAgAgCUEQaiEJIAtBfGoiCw0ACyAFIQkgAyAFRg0BCyADIAlrIQsgASAJQQJ0aiEJA0AgCSAINgIAIAlBBGohCSALQX9qIgsNAAsLIAEgBGohASAGQQFqIgYgAkcNAAsLC74BAwZ/AXsBfwJAIAJFDQAgA0UNACADQQF0IQQgA0F4cSEFQQAhBiADQQhJIQcDQCAAIAZBAXRqLwEAIQhBACEJAkACQCAHDQAgCP0QIQogBSELIAEhCQNAIAkgCv0LAQAgCUEQaiEJIAtBeGoiCw0ACyAFIQkgAyAFRg0BCyADIAlrIQsgASAJQQF0aiEJA0AgCSAIOwEAIAlBAmohCSALQX9qIgsNAAsLIAEgBGohASAGQQFqIgYgAkcNAAsLC48CAQh/AkAgAkUNACADRQ0AIAJBA3EhBEEAIQUCQCACQX9qQQNJDQAgA0EBdCEGIANBAnQhByADQQNsIQggAkF8cSEJQQAhBSABIQIDQCAAIAVqIQoCQCADRSILDQAgAiAKLQAAIAP8CwALAkAgCw0AIAIgA2ogCkEBai0AACAD/AsACwJAIAsNACACIAZqIApBAmotAAAgA/wLAAsCQCALDQAgAiAIaiAKQQNqLQAAIAP8CwALIAIgB2ohAiAJIAVBBGoiBUcNAAsLIARFDQAgACAFaiECIAEgBSADbGohCwNAAkAgA0UNACALIAItAAAgA/wLAAsgCyADaiELIAJBAWohAiAEQX9qIgQNAAsLCw==';

let inst: WebAssembly.Instance | null = null;

function init(): WebAssembly.Instance {
  if (inst) return inst;
  const raw = atob(B64);
  const bytes = new Uint8Array(raw.length);
  for (let i = 0; i < raw.length; i++) bytes[i] = raw.charCodeAt(i);
  inst = new WebAssembly.Instance(new WebAssembly.Module(bytes), {
    env: { memory: getSharedMemory() },
  });
  // Register heap base so runtime knows where safe allocation starts
  const heapBase = inst.exports['__heap_base'];
  if (heapBase && typeof (heapBase as WebAssembly.Global).value === 'number') {
    setHeapBase((heapBase as WebAssembly.Global).value as number);
  }
  return inst;
}

export function repeat_f64(a: number, out: number, N: number, reps: number): void {
  const i = init();
  (i.exports['repeat_f64'] as (...args: number[]) => void)(a, out, N, reps);
}

export function repeat_f32(a: number, out: number, N: number, reps: number): void {
  const i = init();
  (i.exports['repeat_f32'] as (...args: number[]) => void)(a, out, N, reps);
}

export function repeat_i64(a: number, out: number, N: number, reps: number): void {
  const i = init();
  (i.exports['repeat_i64'] as (...args: number[]) => void)(a, out, N, reps);
}

export function repeat_i32(a: number, out: number, N: number, reps: number): void {
  const i = init();
  (i.exports['repeat_i32'] as (...args: number[]) => void)(a, out, N, reps);
}

export function repeat_i16(a: number, out: number, N: number, reps: number): void {
  const i = init();
  (i.exports['repeat_i16'] as (...args: number[]) => void)(a, out, N, reps);
}

export function repeat_i8(a: number, out: number, N: number, reps: number): void {
  const i = init();
  (i.exports['repeat_i8'] as (...args: number[]) => void)(a, out, N, reps);
}
