// AUTO-GENERATED by build:wasm — do not edit. Regenerate with: pnpm run build:wasm

import { getSharedMemory, setHeapBase } from '../runtime';

const B64 =
  'AGFzbQEAAAABCAFgBH9/f38AAg8BA2VudgZtZW1vcnkCAFsDBQQAAAAABAUBcAEBAQYJAX8BQYCA7AILB0IGB3JvbGxfaTgAAAhyb2xsX2kxNgABCHJvbGxfaTMyAAIIcm9sbF9pNjQAAwhyb2xsX2YzMgACCHJvbGxfZjY0AAMK2gMEdgEBfgJAIAJFDQACQCACrSIEQgAgA6wgBIEiBEKAgICAgICAgIB/VhsgBHwiBEIAUg0AIAJFDQEgASAAIAL8CgAADwsgAiAEpyIDayECAkAgA0UNACABIAAgAmogA/wKAAALIAJFDQAgASADaiAAIAL8CgAACwt1AQF+AkAgAkUNAAJAIAKtIgRCACADrCAEgSIEQoCAgICAgICAgH9WGyAEfCIEUA0AIAIgBKciA2shAgJAIANBAXQiA0UNACABIAAgAkEBdGogA/wKAAALIAEgA2ohAQsgAkEBdCICRQ0AIAEgACAC/AoAAAsLdQEBfgJAIAJFDQACQCACrSIEQgAgA6wgBIEiBEKAgICAgICAgIB/VhsgBHwiBFANACACIASnIgNrIQICQCADQQJ0IgNFDQAgASAAIAJBAnRqIAP8CgAACyABIANqIQELIAJBAnQiAkUNACABIAAgAvwKAAALC3UBAX4CQCACRQ0AAkAgAq0iBEIAIAOsIASBIgRCgICAgICAgICAf1YbIAR8IgRQDQAgAiAEpyIDayECAkAgA0EDdCIDRQ0AIAEgACACQQN0aiAD/AoAAAsgASADaiEBCyACQQN0IgJFDQAgASAAIAL8CgAACws=';

let inst: WebAssembly.Instance | null = null;

function init(): WebAssembly.Instance {
  if (inst) return inst;
  const raw = atob(B64);
  const bytes = new Uint8Array(raw.length);
  for (let i = 0; i < raw.length; i++) bytes[i] = raw.charCodeAt(i);
  inst = new WebAssembly.Instance(new WebAssembly.Module(bytes), {
    env: { memory: getSharedMemory() },
  });
  // Register heap base so runtime knows where safe allocation starts
  const heapBase = inst.exports['__heap_base'];
  if (heapBase && typeof (heapBase as WebAssembly.Global).value === 'number') {
    setHeapBase((heapBase as WebAssembly.Global).value as number);
  }
  return inst;
}

export function roll_f64(a: number, out: number, N: number, shift: number): void {
  const i = init();
  (i.exports['roll_f64'] as (...args: number[]) => void)(a, out, N, shift);
}

export function roll_f32(a: number, out: number, N: number, shift: number): void {
  const i = init();
  (i.exports['roll_f32'] as (...args: number[]) => void)(a, out, N, shift);
}

export function roll_i64(a: number, out: number, N: number, shift: number): void {
  const i = init();
  (i.exports['roll_i64'] as (...args: number[]) => void)(a, out, N, shift);
}

export function roll_i32(a: number, out: number, N: number, shift: number): void {
  const i = init();
  (i.exports['roll_i32'] as (...args: number[]) => void)(a, out, N, shift);
}

export function roll_i16(a: number, out: number, N: number, shift: number): void {
  const i = init();
  (i.exports['roll_i16'] as (...args: number[]) => void)(a, out, N, shift);
}

export function roll_i8(a: number, out: number, N: number, shift: number): void {
  const i = init();
  (i.exports['roll_i8'] as (...args: number[]) => void)(a, out, N, shift);
}
