// AUTO-GENERATED by build:wasm — do not edit. Regenerate with: npm run build:wasm

import { getSharedMemory, setHeapBase } from '../runtime';

const B64 =
  'AGFzbQEAAAABCgFgBn9/f39/fwACDwEDZW52Bm1lbW9yeQIAcgMEAwAAAAYJAX8BQYCAyAMLB0UDFXVucmF2ZWxfaW5kZXhfaTMyX2Y2NAAAFXVucmF2ZWxfaW5kZXhfaTY0X2Y2NAABEXVucmF2ZWxfaW5kZXhfZjY0AAIKzAMDkgEBCX8CQCACRQ0AIAVFDQAgAkEDdCEGQQAhBwNAIAAgB0ECdGooAgAhCCADIQkgASEKIAQhCyAFIQwDQCAKIAggCSgCACINbSIOIAsoAgBvtzkDACAJQQRqIQkgCiAGaiEKIAtBBGohCyAIIA4gDWxrIQggDEF/aiIMDQALIAFBCGohASAHQQFqIgcgAkcNAAsLC5gBBAJ/AX4EfwJ+AkAgAkUNACAFRQ0AIAJBA3QhBkEAIQcDQCAAIAdBA3RqKQMAIQggAyEJIAEhCiAEIQsgBSEMA0AgCiAIIAkpAwAiDX8iDiALKQMAgbk5AwAgCUEIaiEJIAogBmohCiALQQhqIQsgCCAOIA1+fSEIIAxBf2oiDA0ACyABQQhqIQEgB0EBaiIHIAJHDQALCwubAQQCfwF+BH8CfgJAIAJFDQAgBUUNACACQQN0IQZBACEHA0AgACAHQQN0aisDAPwGIQggAyEJIAEhCiAEIQsgBSEMA0AgCiAIIAkoAgCsIg1/Ig4gCzQCAIG5OQMAIAlBBGohCSAKIAZqIQogC0EEaiELIAggDiANfn0hCCAMQX9qIgwNAAsgAUEIaiEBIAdBAWoiByACRw0ACwsL';

let inst: WebAssembly.Instance | null = null;

function init(): WebAssembly.Instance {
  if (inst) return inst;
  const raw = atob(B64);
  const bytes = new Uint8Array(raw.length);
  for (let i = 0; i < raw.length; i++) bytes[i] = raw.charCodeAt(i);
  inst = new WebAssembly.Instance(new WebAssembly.Module(bytes), {
    env: { memory: getSharedMemory() },
  });
  // Register heap base so runtime knows where safe allocation starts
  const heapBase = inst.exports['__heap_base'];
  if (heapBase && typeof (heapBase as WebAssembly.Global).value === 'number') {
    setHeapBase((heapBase as WebAssembly.Global).value as number);
  }
  return inst;
}

export function unravel_index_i32_f64(
  indices: number,
  out: number,
  N: number,
  strides: number,
  shape: number,
  ndim: number
): void {
  const i = init();
  (i.exports['unravel_index_i32_f64'] as (...args: number[]) => void)(
    indices,
    out,
    N,
    strides,
    shape,
    ndim
  );
}

export function unravel_index_i64_f64(
  indices: number,
  out: number,
  N: number,
  strides: number,
  shape: number,
  ndim: number
): void {
  const i = init();
  (i.exports['unravel_index_i64_f64'] as (...args: number[]) => void)(
    indices,
    out,
    N,
    strides,
    shape,
    ndim
  );
}

export function unravel_index_f64(
  indices: number,
  out: number,
  N: number,
  strides: number,
  shape: number,
  ndim: number
): void {
  const i = init();
  (i.exports['unravel_index_f64'] as (...args: number[]) => void)(
    indices,
    out,
    N,
    strides,
    shape,
    ndim
  );
}
