// AUTO-GENERATED by build:wasm — do not edit. Regenerate with: npm run build:wasm

import { getSharedMemory, setHeapBase } from '../runtime';

const B64 =
  'AGFzbQEAAAABCAFgBH9/f38AAg8BA2VudgZtZW1vcnkCAGQDAwIAAAQFAXABAQEGCQF/AUGAgJADCwcYAgh2ZG90X2M2NAAACXZkb3RfYzEyOAABCrECAo4BAQZ9AkACQCADDQBDAAAAACEEQwAAAAAhBQwBC0MAAAAAIQVDAAAAACEEA0AgBSAAKgIAIgYgAUEEaioCACIHlCAAQQRqKgIAIgggASoCACIJlJOSIQUgBCAGIAmUIAggB5SSkiEEIAFBCGohASAAQQhqIQAgA0F/aiIDDQALCyACIAU4AgQgAiAEOAIAC54BAQZ8AkACQCADDQBEAAAAAAAAAAAhBEQAAAAAAAAAACEFDAELRAAAAAAAAAAAIQVEAAAAAAAAAAAhBANAIAUgACsDACIGIAFBCGorAwAiB6IgAEEIaisDACIIIAErAwAiCaKhoCEFIAQgBiAJoiAIIAeioKAhBCABQRBqIQEgAEEQaiEAIANBf2oiAw0ACwsgAiAFOQMIIAIgBDkDAAs=';

let inst: WebAssembly.Instance | null = null;

function init(): WebAssembly.Instance {
  if (inst) return inst;
  const raw = atob(B64);
  const bytes = new Uint8Array(raw.length);
  for (let i = 0; i < raw.length; i++) bytes[i] = raw.charCodeAt(i);
  inst = new WebAssembly.Instance(new WebAssembly.Module(bytes), {
    env: { memory: getSharedMemory() },
  });
  // Register heap base so runtime knows where safe allocation starts
  const heapBase = inst.exports['__heap_base'];
  if (heapBase && typeof (heapBase as WebAssembly.Global).value === 'number') {
    setHeapBase((heapBase as WebAssembly.Global).value as number);
  }
  return inst;
}

export function vdot_c128(a: number, b: number, out: number, K: number): void {
  const i = init();
  (i.exports['vdot_c128'] as (...args: number[]) => void)(a, b, out, K);
}

export function vdot_c64(a: number, b: number, out: number, K: number): void {
  const i = init();
  (i.exports['vdot_c64'] as (...args: number[]) => void)(a, b, out, K);
}
