// AUTO-GENERATED by build:wasm — do not edit. Regenerate with: npm run build:wasm

import { getSharedMemory, setHeapBase } from '../runtime';

const B64 =
  'AGFzbQEAAAABDQJgAn9/AXxgAn9/AX0CDwEDZW52Bm1lbW9yeQIAfgMDAgABBgkBfwFBgID4AwsHJwIQdmVjdG9yX25vcm0yX2Y2NAAAEHZlY3Rvcl9ub3JtMl9mMzIAAQq5CAKSBAUBfwF7BH8BewJ8AkACQCABQX5xIgINAP0MAAAAAAAAAAAAAAAAAAAAACEDQQAhBAwBCyACQX9qIgVBAXZBAWoiBkEDcSEHAkACQCACQQdPDQBBACEG/QwAAAAAAAAAAAAAAAAAAAAAIQMMAQsgBkF8cSEEQQAhBv0MAAAAAAAAAAAAAAAAAAAAACEDIAAhAgNAIAMgAv0AAwAiCCAI/fIB/fABIAJBEGr9AAMAIgMgA/3yAf3wASACQSBq/QADACIDIAP98gH98AEgAkEwav0AAwAiAyAD/fIB/fABIQMgAkHAAGohAiAGQQhqIQYgBEF8aiIEDQALCyAFQX5xIQQCQCAHRQ0AIAAgBkEDdGohAgNAIAMgAv0AAwAiCCAI/fIB/fABIQMgAkEQaiECIAdBf2oiBw0ACwsgBEECaiEECyAD/SEAIAP9IQGgIQkCQCAEIAFPDQACQAJAIAEgBGtBA3EiBg0AIAQhBwwBCyAAIARBA3RqIQIgBCEHA0AgB0EBaiEHIAkgAisDACIKIAqioCEJIAJBCGohAiAGQX9qIgYNAAsLIAQgAWtBfEsNACABIAdrIQYgACAHQQN0aiECA0AgCSACKwMAIgogCqKgIAJBCGorAwAiCSAJoqAgAkEQaisDACIJIAmioCACQRhqKwMAIgkgCaKgIQkgAkEgaiECIAZBfGoiBg0ACwsgCZ8LogQFAX8BewR/AXsCfQJAAkAgAUF8cSICDQD9DAAAAAAAAAAAAAAAAAAAAAAhA0EAIQQMAQsgAkF/aiIFQQJ2QQFqIgZBA3EhBwJAAkAgAkENTw0AQQAhBv0MAAAAAAAAAAAAAAAAAAAAACEDDAELIAZB/P///wdxIQRBACEG/QwAAAAAAAAAAAAAAAAAAAAAIQMgACECA0AgAyAC/QACACIIIAj95gH95AEgAkEQav0AAgAiAyAD/eYB/eQBIAJBIGr9AAIAIgMgA/3mAf3kASACQTBq/QACACIDIAP95gH95AEhAyACQcAAaiECIAZBEGohBiAEQXxqIgQNAAsLIAVBfHEhBAJAIAdFDQAgACAGQQJ0aiECA0AgAyAC/QACACIIIAj95gH95AEhAyACQRBqIQIgB0F/aiIHDQALCyAEQQRqIQQLIAP9HwMgA/0fAiAD/R8AIAP9HwGSkpIhCQJAIAQgAU8NAAJAAkAgASAEa0EDcSIGDQAgBCEHDAELIAAgBEECdGohAiAEIQcDQCAHQQFqIQcgCSACKgIAIgogCpSSIQkgAkEEaiECIAZBf2oiBg0ACwsgBCABa0F8Sw0AIAEgB2shBiAAIAdBAnRqIQIDQCAJIAIqAgAiCiAKlJIgAkEEaioCACIJIAmUkiACQQhqKgIAIgkgCZSSIAJBDGoqAgAiCSAJlJIhCSACQRBqIQIgBkF8aiIGDQALCyAJkQs=';

let inst: WebAssembly.Instance | null = null;

function init(): WebAssembly.Instance {
  if (inst) return inst;
  const raw = atob(B64);
  const bytes = new Uint8Array(raw.length);
  for (let i = 0; i < raw.length; i++) bytes[i] = raw.charCodeAt(i);
  inst = new WebAssembly.Instance(new WebAssembly.Module(bytes), {
    env: { memory: getSharedMemory() },
  });
  // Register heap base so runtime knows where safe allocation starts
  const heapBase = inst.exports['__heap_base'];
  if (heapBase && typeof (heapBase as WebAssembly.Global).value === 'number') {
    setHeapBase((heapBase as WebAssembly.Global).value as number);
  }
  return inst;
}

export function vector_norm2_f64(a: number, N: number): number {
  const i = init();
  return (i.exports['vector_norm2_f64'] as (...args: number[]) => number)(a, N);
}

export function vector_norm2_f32(a: number, N: number): number {
  const i = init();
  return (i.exports['vector_norm2_f32'] as (...args: number[]) => number)(a, N);
}
