// AUTO-GENERATED by build:wasm — do not edit. Regenerate with: npm run build:wasm

import { getSharedMemory, setHeapBase } from '../runtime';

const B64 =
  'AGFzbQEAAAABDQJgAn9/AX1gAn9/AXwCDwEDZW52Bm1lbW9yeQIAfwMDAgABBAUBcAEBAQYJAX8BQYCA/AMLBycCEHZlY3Rvcl9ub3JtMl9mMzIAABB2ZWN0b3Jfbm9ybTJfZjY0AAEKswgCnwQFAX8BewR/AXsCfQJAAkAgAUF8cSICDQD9DAAAAAAAAAAAAAAAAAAAAAAhA0EAIQQMAQsgAkF/akECdkEBaiIFQQNxIQYCQAJAIAJBDU8NAEEAIQf9DAAAAAAAAAAAAAAAAAAAAAAhAwwBCyAFQfz///8HcSEEQQAhB/0MAAAAAAAAAAAAAAAAAAAAACEDIAAhBQNAIAMgBf0AAAAiCCAI/eYB/eQBIAVBEGr9AAAAIgMgA/3mAf3kASAFQSBq/QAAACIDIAP95gH95AEgBUEwav0AAAAiAyAD/eYB/eQBIQMgBUHAAGohBSAHQRBqIQcgBEF8aiIEDQALCwJAIAZFDQAgACAHQQJ0aiEFA0AgAyAF/QAAACIIIAj95gH95AEhAyAFQRBqIQUgBkF/aiIGDQALCyACQX9qQXxxQQRqIQQLIAP9HwMgA/0fAiAD/R8AIAP9HwGSkpIhCQJAIAQgAU8NAAJAAkAgASAEa0EDcSIHDQAgBCEGDAELIAAgBEECdGohBSAEIQYDQCAGQQFqIQYgCSAFKgIAIgogCpSSIQkgBUEEaiEFIAdBf2oiBw0ACwsgBCABa0F8Sw0AIAEgBmshByAAIAZBAnRqIQUDQCAJIAUqAgAiCiAKlJIgBUEEaioCACIJIAmUkiAFQQhqKgIAIgkgCZSSIAVBDGoqAgAiCSAJlJIhCSAFQRBqIQUgB0F8aiIHDQALCyAJkQuPBAUBfwF7BH8BewJ8AkACQCABQX5xIgINAP0MAAAAAAAAAAAAAAAAAAAAACEDQQAhBAwBCyACQX9qQQF2QQFqIgVBA3EhBgJAAkAgAkEHTw0AQQAhB/0MAAAAAAAAAAAAAAAAAAAAACEDDAELIAVBfHEhBEEAIQf9DAAAAAAAAAAAAAAAAAAAAAAhAyAAIQUDQCADIAX9AAMAIgggCP3yAf3wASAFQRBq/QADACIDIAP98gH98AEgBUEgav0AAwAiAyAD/fIB/fABIAVBMGr9AAMAIgMgA/3yAf3wASEDIAVBwABqIQUgB0EIaiEHIARBfGoiBA0ACwsCQCAGRQ0AIAAgB0EDdGohBQNAIAMgBf0AAwAiCCAI/fIB/fABIQMgBUEQaiEFIAZBf2oiBg0ACwsgAkF/akF+cUECaiEECyAD/SEAIAP9IQGgIQkCQCAEIAFPDQACQAJAIAEgBGtBA3EiBw0AIAQhBgwBCyAAIARBA3RqIQUgBCEGA0AgBkEBaiEGIAkgBSsDACIKIAqioCEJIAVBCGohBSAHQX9qIgcNAAsLIAQgAWtBfEsNACABIAZrIQcgACAGQQN0aiEFA0AgCSAFKwMAIgogCqKgIAVBCGorAwAiCSAJoqAgBUEQaisDACIJIAmioCAFQRhqKwMAIgkgCaKgIQkgBUEgaiEFIAdBfGoiBw0ACwsgCZ8L';

let inst: WebAssembly.Instance | null = null;

function init(): WebAssembly.Instance {
  if (inst) return inst;
  const raw = atob(B64);
  const bytes = new Uint8Array(raw.length);
  for (let i = 0; i < raw.length; i++) bytes[i] = raw.charCodeAt(i);
  inst = new WebAssembly.Instance(new WebAssembly.Module(bytes), {
    env: { memory: getSharedMemory() },
  });
  // Register heap base so runtime knows where safe allocation starts
  const heapBase = inst.exports['__heap_base'];
  if (heapBase && typeof (heapBase as WebAssembly.Global).value === 'number') {
    setHeapBase((heapBase as WebAssembly.Global).value as number);
  }
  return inst;
}

export function vector_norm2_f64(a: number, N: number): number {
  const i = init();
  return (i.exports['vector_norm2_f64'] as (...args: number[]) => number)(a, N);
}

export function vector_norm2_f32(a: number, N: number): number {
  const i = init();
  return (i.exports['vector_norm2_f32'] as (...args: number[]) => number)(a, N);
}
