// AUTO-GENERATED by build:wasm — do not edit. Regenerate with: npm run build:wasm

import { getSharedMemory, setHeapBase } from '../runtime';

const B64 =
  'AGFzbQEAAAABDQJgAn9/AX1gAn9/AXwCEAEDZW52Bm1lbW9yeQIAhQEDAwIAAQQFAXABAQEGCQF/AUGAgJQECwcnAhB2ZWN0b3Jfbm9ybTJfZjMyAAAQdmVjdG9yX25vcm0yX2Y2NAABCpUIApAEBQF/AXsEfwR7An0CQAJAIAFBfHEiAg0A/QwAAAAAAAAAAAAAAAAAAAAAIQNBACEEDAELIAJBf2pBAnZBAWoiBUEDcSEGAkACQCACQQ1PDQBBACEH/QwAAAAAAAAAAAAAAAAAAAAAIQMMAQsgBUH8////B3EhBEEAIQf9DAAAAAAAAAAAAAAAAAAAAAAhAyAAIQUDQCAFQTBq/QAAACIIIAggBUEgav0AAAAiCSAJIAVBEGr9AAAAIgogCiAF/QAAACILIAsgA/2FAv2FAv2FAv2FAiEDIAVBwABqIQUgB0EQaiEHIARBfGoiBA0ACwsCQCAGRQ0AIAAgB0ECdGohBQNAIAX9AAAAIgggCCAD/YUCIQMgBUEQaiEFIAZBf2oiBg0ACwsgAkF/akF8cUEEaiEECyAD/R8DIAP9HwIgA/0fACAD/R8BkpKSIQwCQCAEIAFPDQACQAJAIAEgBGtBA3EiBw0AIAQhBgwBCyAAIARBAnRqIQUgBCEGA0AgBkEBaiEGIAwgBSoCACINIA2UkiEMIAVBBGohBSAHQX9qIgcNAAsLIAQgAWtBfEsNACABIAZrIQcgACAGQQJ0aiEFA0AgDCAFKgIAIg0gDZSSIAVBBGoqAgAiDCAMlJIgBUEIaioCACIMIAyUkiAFQQxqKgIAIgwgDJSSIQwgBUEQaiEFIAdBfGoiBw0ACwsgDJELgAQFAX8BewR/BHsCfAJAAkAgAUF+cSICDQD9DAAAAAAAAAAAAAAAAAAAAAAhA0EAIQQMAQsgAkF/akEBdkEBaiIFQQNxIQYCQAJAIAJBB08NAEEAIQf9DAAAAAAAAAAAAAAAAAAAAAAhAwwBCyAFQXxxIQRBACEH/QwAAAAAAAAAAAAAAAAAAAAAIQMgACEFA0AgBUEwav0AAwAiCCAIIAVBIGr9AAMAIgkgCSAFQRBq/QADACIKIAogBf0AAwAiCyALIAP9hwL9hwL9hwL9hwIhAyAFQcAAaiEFIAdBCGohByAEQXxqIgQNAAsLAkAgBkUNACAAIAdBA3RqIQUDQCAF/QADACIIIAggA/2HAiEDIAVBEGohBSAGQX9qIgYNAAsLIAJBf2pBfnFBAmohBAsgA/0hACAD/SEBoCEMAkAgBCABTw0AAkACQCABIARrQQNxIgcNACAEIQYMAQsgACAEQQN0aiEFIAQhBgNAIAZBAWohBiAMIAUrAwAiDSANoqAhDCAFQQhqIQUgB0F/aiIHDQALCyAEIAFrQXxLDQAgASAGayEHIAAgBkEDdGohBQNAIAwgBSsDACINIA2ioCAFQQhqKwMAIgwgDKKgIAVBEGorAwAiDCAMoqAgBUEYaisDACIMIAyioCEMIAVBIGohBSAHQXxqIgcNAAsLIAyfCw==';

let inst: WebAssembly.Instance | null = null;

function init(): WebAssembly.Instance {
  if (inst) return inst;
  const raw = atob(B64);
  const bytes = new Uint8Array(raw.length);
  for (let i = 0; i < raw.length; i++) bytes[i] = raw.charCodeAt(i);
  inst = new WebAssembly.Instance(new WebAssembly.Module(bytes), {
    env: { memory: getSharedMemory() },
  });
  // Register heap base so runtime knows where safe allocation starts
  const heapBase = inst.exports['__heap_base'];
  if (heapBase && typeof (heapBase as WebAssembly.Global).value === 'number') {
    setHeapBase((heapBase as WebAssembly.Global).value as number);
  }
  return inst;
}

export function vector_norm2_f64(a: number, N: number): number {
  const i = init();
  return (i.exports['vector_norm2_f64'] as (...args: number[]) => number)(a, N);
}

export function vector_norm2_f32(a: number, N: number): number {
  const i = init();
  return (i.exports['vector_norm2_f32'] as (...args: number[]) => number)(a, N);
}
