// AUTO-GENERATED by build:wasm — do not edit. Regenerate with: npm run build:wasm

import { getSharedMemory, setHeapBase } from '../runtime';

const B64 =
  'AGFzbQEAAAABDQJgAn9/AX1gAn9/AXwCDwEDZW52Bm1lbW9yeQIAfgMDAgABBAUBcAEBAQYJAX8BQYCA9gMLBycCEHZlY3Rvcl9ub3JtMl9mMzIAABB2ZWN0b3Jfbm9ybTJfZjY0AAEKlQgCkAQFAX8BewR/BHsCfQJAAkAgAUF8cSICDQD9DAAAAAAAAAAAAAAAAAAAAAAhA0EAIQQMAQsgAkF/akECdkEBaiIFQQNxIQYCQAJAIAJBDU8NAEEAIQf9DAAAAAAAAAAAAAAAAAAAAAAhAwwBCyAFQfz///8HcSEEQQAhB/0MAAAAAAAAAAAAAAAAAAAAACEDIAAhBQNAIAVBMGr9AAAAIgggCCAFQSBq/QAAACIJIAkgBUEQav0AAAAiCiAKIAX9AAAAIgsgCyAD/YUC/YUC/YUC/YUCIQMgBUHAAGohBSAHQRBqIQcgBEF8aiIEDQALCwJAIAZFDQAgACAHQQJ0aiEFA0AgBf0AAAAiCCAIIAP9hQIhAyAFQRBqIQUgBkF/aiIGDQALCyACQX9qQXxxQQRqIQQLIAP9HwMgA/0fAiAD/R8AIAP9HwGSkpIhDAJAIAQgAU8NAAJAAkAgASAEa0EDcSIHDQAgBCEGDAELIAAgBEECdGohBSAEIQYDQCAGQQFqIQYgDCAFKgIAIg0gDZSSIQwgBUEEaiEFIAdBf2oiBw0ACwsgBCABa0F8Sw0AIAEgBmshByAAIAZBAnRqIQUDQCAMIAUqAgAiDSANlJIgBUEEaioCACIMIAyUkiAFQQhqKgIAIgwgDJSSIAVBDGoqAgAiDCAMlJIhDCAFQRBqIQUgB0F8aiIHDQALCyAMkQuABAUBfwF7BH8EewJ8AkACQCABQX5xIgINAP0MAAAAAAAAAAAAAAAAAAAAACEDQQAhBAwBCyACQX9qQQF2QQFqIgVBA3EhBgJAAkAgAkEHTw0AQQAhB/0MAAAAAAAAAAAAAAAAAAAAACEDDAELIAVBfHEhBEEAIQf9DAAAAAAAAAAAAAAAAAAAAAAhAyAAIQUDQCAFQTBq/QADACIIIAggBUEgav0AAwAiCSAJIAVBEGr9AAMAIgogCiAF/QADACILIAsgA/2HAv2HAv2HAv2HAiEDIAVBwABqIQUgB0EIaiEHIARBfGoiBA0ACwsCQCAGRQ0AIAAgB0EDdGohBQNAIAX9AAMAIgggCCAD/YcCIQMgBUEQaiEFIAZBf2oiBg0ACwsgAkF/akF+cUECaiEECyAD/SEAIAP9IQGgIQwCQCAEIAFPDQACQAJAIAEgBGtBA3EiBw0AIAQhBgwBCyAAIARBA3RqIQUgBCEGA0AgBkEBaiEGIAwgBSsDACINIA2ioCEMIAVBCGohBSAHQX9qIgcNAAsLIAQgAWtBfEsNACABIAZrIQcgACAGQQN0aiEFA0AgDCAFKwMAIg0gDaKgIAVBCGorAwAiDCAMoqAgBUEQaisDACIMIAyioCAFQRhqKwMAIgwgDKKgIQwgBUEgaiEFIAdBfGoiBw0ACwsgDJ8L';

let inst: WebAssembly.Instance | null = null;

function init(): WebAssembly.Instance {
  if (inst) return inst;
  const raw = atob(B64);
  const bytes = new Uint8Array(raw.length);
  for (let i = 0; i < raw.length; i++) bytes[i] = raw.charCodeAt(i);
  inst = new WebAssembly.Instance(new WebAssembly.Module(bytes), {
    env: { memory: getSharedMemory() },
  });
  // Register heap base so runtime knows where safe allocation starts
  const heapBase = inst.exports['__heap_base'];
  if (heapBase && typeof (heapBase as WebAssembly.Global).value === 'number') {
    setHeapBase((heapBase as WebAssembly.Global).value as number);
  }
  return inst;
}

export function vector_norm2_f64(a: number, N: number): number {
  const i = init();
  return (i.exports['vector_norm2_f64'] as (...args: number[]) => number)(a, N);
}

export function vector_norm2_f32(a: number, N: number): number {
  const i = init();
  return (i.exports['vector_norm2_f32'] as (...args: number[]) => number)(a, N);
}
