// AUTO-GENERATED by build:wasm — do not edit. Regenerate with: npm run build:wasm

import { getSharedMemory, setHeapBase } from '../runtime';

const B64 =
  'AGFzbQEAAAABDQJgAn9/AXxgAn9/AX0CDwEDZW52Bm1lbW9yeQIAfwMDAgABBgkBfwFBgID8AwsHJwIQdmVjdG9yX25vcm0yX2Y2NAAAEHZlY3Rvcl9ub3JtMl9mMzIAAQqbCAKDBAUBfwF7BH8EewJ8AkACQCABQX5xIgINAP0MAAAAAAAAAAAAAAAAAAAAACEDQQAhBAwBCyACQX9qIgVBAXZBAWoiBkEDcSEHAkACQCACQQdPDQBBACEG/QwAAAAAAAAAAAAAAAAAAAAAIQMMAQsgBkF8cSEEQQAhBv0MAAAAAAAAAAAAAAAAAAAAACEDIAAhAgNAIAJBMGr9AAMAIgggCCACQSBq/QADACIJIAkgAkEQav0AAwAiCiAKIAL9AAMAIgsgCyAD/YcC/YcC/YcC/YcCIQMgAkHAAGohAiAGQQhqIQYgBEF8aiIEDQALCyAFQX5xIQQCQCAHRQ0AIAAgBkEDdGohAgNAIAL9AAMAIgggCCAD/YcCIQMgAkEQaiECIAdBf2oiBw0ACwsgBEECaiEECyAD/SEAIAP9IQGgIQwCQCAEIAFPDQACQAJAIAEgBGtBA3EiBg0AIAQhBwwBCyAAIARBA3RqIQIgBCEHA0AgB0EBaiEHIAwgAisDACINIA2ioCEMIAJBCGohAiAGQX9qIgYNAAsLIAQgAWtBfEsNACABIAdrIQYgACAHQQN0aiECA0AgDCACKwMAIg0gDaKgIAJBCGorAwAiDCAMoqAgAkEQaisDACIMIAyioCACQRhqKwMAIgwgDKKgIQwgAkEgaiECIAZBfGoiBg0ACwsgDJ8LkwQFAX8BewR/BHsCfQJAAkAgAUF8cSICDQD9DAAAAAAAAAAAAAAAAAAAAAAhA0EAIQQMAQsgAkF/aiIFQQJ2QQFqIgZBA3EhBwJAAkAgAkENTw0AQQAhBv0MAAAAAAAAAAAAAAAAAAAAACEDDAELIAZB/P///wdxIQRBACEG/QwAAAAAAAAAAAAAAAAAAAAAIQMgACECA0AgAkEwav0AAgAiCCAIIAJBIGr9AAIAIgkgCSACQRBq/QACACIKIAogAv0AAgAiCyALIAP9hQL9hQL9hQL9hQIhAyACQcAAaiECIAZBEGohBiAEQXxqIgQNAAsLIAVBfHEhBAJAIAdFDQAgACAGQQJ0aiECA0AgAv0AAgAiCCAIIAP9hQIhAyACQRBqIQIgB0F/aiIHDQALCyAEQQRqIQQLIAP9HwMgA/0fAiAD/R8AIAP9HwGSkpIhDAJAIAQgAU8NAAJAAkAgASAEa0EDcSIGDQAgBCEHDAELIAAgBEECdGohAiAEIQcDQCAHQQFqIQcgDCACKgIAIg0gDZSSIQwgAkEEaiECIAZBf2oiBg0ACwsgBCABa0F8Sw0AIAEgB2shBiAAIAdBAnRqIQIDQCAMIAIqAgAiDSANlJIgAkEEaioCACIMIAyUkiACQQhqKgIAIgwgDJSSIAJBDGoqAgAiDCAMlJIhDCACQRBqIQIgBkF8aiIGDQALCyAMkQs=';

let inst: WebAssembly.Instance | null = null;

function init(): WebAssembly.Instance {
  if (inst) return inst;
  const raw = atob(B64);
  const bytes = new Uint8Array(raw.length);
  for (let i = 0; i < raw.length; i++) bytes[i] = raw.charCodeAt(i);
  inst = new WebAssembly.Instance(new WebAssembly.Module(bytes), {
    env: { memory: getSharedMemory() },
  });
  // Register heap base so runtime knows where safe allocation starts
  const heapBase = inst.exports['__heap_base'];
  if (heapBase && typeof (heapBase as WebAssembly.Global).value === 'number') {
    setHeapBase((heapBase as WebAssembly.Global).value as number);
  }
  return inst;
}

export function vector_norm2_f64(a: number, N: number): number {
  const i = init();
  return (i.exports['vector_norm2_f64'] as (...args: number[]) => number)(a, N);
}

export function vector_norm2_f32(a: number, N: number): number {
  const i = init();
  return (i.exports['vector_norm2_f32'] as (...args: number[]) => number)(a, N);
}
