/**
 * WASM Build Script
 *
 * Compiles Zig kernels to .wasm, base64-encodes them, and generates
 * TypeScript wrapper modules in src/common/wasm/bins/.
 *
 * Usage: tsx scripts/build-wasm.ts [--safe]
 *
 * Requires Zig installed. If Zig is not found, exits with a warning
 * (checked-in .wasm.ts files will be used as-is).
 */

import { execSync, execFileSync } from 'child_process';
import { readdirSync, readFileSync, writeFileSync, mkdirSync, rmSync } from 'fs';
import { join } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = join(__filename, '..');
const ROOT = join(__dirname, '..');

const ZIG_DIR = join(ROOT, 'src/common/wasm/zig');
const BINS_DIR = join(ROOT, 'src/common/wasm/bins');
const TMP_DIR = join(ROOT, '.wasm-tmp');

// --safe flag: compile with ReleaseSafe (bounds checks, overflow detection)
const SAFE_MODE = process.argv.includes('--safe');
const ZIG_OPT = SAFE_MODE ? 'ReleaseSafe' : 'ReleaseFast';

// --- Check for Zig ---

try {
  const version = execSync('zig version', { encoding: 'utf-8' }).trim();
  console.log(`Found Zig ${version}`);
} catch {
  console.warn('WARNING: Zig not found — skipping WASM build.');
  console.warn('Checked-in .wasm.ts files will be used. Install Zig to rebuild.');
  process.exit(0);
}

// --- Parse Zig exports ---

function parseZigExports(
  zigSource: string
): { name: string; params: string; returnType: string }[] {
  const exports: { name: string; params: string; returnType: string }[] = [];
  const regex = /^export fn (\w+)\(([^)]*)\)\s*(\w+)/gm;
  let match;
  while ((match = regex.exec(zigSource)) !== null) {
    const zigRet = match[3]!;
    // Map Zig integer return types to TS 'number', void stays void
    const returnType = zigRet === 'void' ? 'void' : 'number';
    exports.push({ name: match[1]!, params: match[2]!, returnType });
  }
  return exports;
}

/**
 * Parse Zig function parameters into TypeScript parameter types and detect i64/u64 params.
 * All WASM numeric params become `number` in TypeScript.
 * Returns both the TS param string and a set of param names that are i64/u64.
 */
function zigParamsToTs(params: string): { tsParams: string; bigintParams: Set<string> } {
  if (!params.trim()) return { tsParams: '', bigintParams: new Set() };
  const bigintParams = new Set<string>();
  const tsParams = params
    .split(',')
    .map((p) => {
      const parts = p.trim().split(':');
      const name = parts[0]!.trim();
      const zigType = parts.slice(1).join(':').trim();
      // Skip comptime params
      if (name.startsWith('comptime')) return null;
      // Detect i64/u64 scalar params (not pointers)
      if ((zigType === 'i64' || zigType === 'u64') && !zigType.includes('[*]')) {
        bigintParams.add(name);
      }
      return `${name}: number`;
    })
    .filter(Boolean)
    .join(', ');
  return { tsParams, bigintParams };
}

// --- Generate .wasm.ts module ---

function generateWasmTs(
  kernelName: string,
  base64: string,
  exports: { name: string; params: string }[]
): string {
  const lines: string[] = [];

  lines.push(`// AUTO-GENERATED by build:wasm — do not edit. Regenerate with: npm run build:wasm`);
  lines.push(``);
  lines.push(`import { getSharedMemory, setHeapBase } from '../runtime';`);
  lines.push(``);
  lines.push(`const B64 = "${base64}";`);
  lines.push(``);
  lines.push(`let inst: WebAssembly.Instance | null = null;`);
  lines.push(``);
  lines.push(`function init(): WebAssembly.Instance {`);
  lines.push(`  if (inst) return inst;`);
  lines.push(`  const raw = atob(B64);`);
  lines.push(`  const bytes = new Uint8Array(raw.length);`);
  lines.push(`  for (let i = 0; i < raw.length; i++) bytes[i] = raw.charCodeAt(i);`);
  lines.push(`  inst = new WebAssembly.Instance(`);
  lines.push(`    new WebAssembly.Module(bytes),`);
  lines.push(`    { env: { memory: getSharedMemory() } }`);
  lines.push(`  );`);
  lines.push(`  // Register heap base so runtime knows where safe allocation starts`);
  lines.push(`  const heapBase = inst.exports['__heap_base'];`);
  lines.push(`  if (heapBase && typeof (heapBase as WebAssembly.Global).value === 'number') {`);
  lines.push(`    setHeapBase((heapBase as WebAssembly.Global).value as number);`);
  lines.push(`  }`);
  lines.push(`  return inst;`);
  lines.push(`}`);
  lines.push(``);

  for (const exp of exports) {
    const { tsParams, bigintParams } = zigParamsToTs(exp.params);
    const ret = exp.returnType;
    const retPrefix = ret === 'void' ? '' : 'return ';
    lines.push(`export function ${exp.name}(${tsParams}): ${ret} {`);
    lines.push(`  const i = init();`);
    const argNames = tsParams
      ? tsParams
          .split(',')
          .map((p) => p.trim().split(':')[0]!.trim())
          .join(', ')
      : '';
    if (bigintParams.size > 0) {
      // Some params need BigInt conversion for WASM i64 params
      const castArgs = tsParams
        ? tsParams
            .split(',')
            .map((p) => {
              const name = p.trim().split(':')[0]!.trim();
              return bigintParams.has(name) ? `BigInt(Math.round(${name}))` : name;
            })
            .join(', ')
        : '';
      lines.push(
        `  ${retPrefix}(i.exports['${exp.name}'] as (...args: (number | bigint)[]) => ${ret})(${castArgs});`
      );
    } else {
      lines.push(
        `  ${retPrefix}(i.exports['${exp.name}'] as (...args: number[]) => ${ret})(${argNames});`
      );
    }
    lines.push(`}`);
    lines.push(``);
  }

  return lines.join('\n');
}

// --- Main build ---

mkdirSync(TMP_DIR, { recursive: true });
mkdirSync(BINS_DIR, { recursive: true });

const zigFiles = readdirSync(ZIG_DIR).filter(
  (f) => f.endsWith('.zig') && f !== 'simd.zig'
);

console.log(`Building ${zigFiles.length} WASM kernel(s) [${ZIG_OPT}]...\n`);

// --- Run Zig tests ---

console.log('Running Zig tests...\n');

for (const file of zigFiles) {
  const zigPath = join(ZIG_DIR, file);
  console.log(`  Testing ${file}...`);
  try {
    execFileSync('zig', ['test', zigPath], { stdio: 'pipe', cwd: ZIG_DIR });
    console.log(`  ✓ ${file} — all tests passed`);
  } catch (err: unknown) {
    const error = err as { stderr?: Buffer; stdout?: Buffer };
    console.error(`  ✗ ${file} — tests FAILED:`);
    console.error(error.stderr?.toString() ?? error.stdout?.toString() ?? '');
    process.exit(1);
  }
}

console.log('');

// --- Compile to WASM ---

for (const file of zigFiles) {
  const name = file.replace('.zig', '');
  const zigPath = join(ZIG_DIR, file);
  const wasmPath = join(TMP_DIR, `${name}.wasm`);

  // Compile Zig -> .wasm
  console.log(`  Compiling ${file}...`);
  try {
    const zigArgs = [
        'build-exe',
        zigPath,
        '-target', 'wasm32-freestanding',
        '-O', ZIG_OPT,
        '-mcpu=generic+simd128',
        '-fno-entry',
        '-rdynamic',
        `--import-memory`,
        `-femit-bin=${wasmPath}`,
      ];
    if (!SAFE_MODE) zigArgs.push('-fstrip');
    execFileSync('zig', zigArgs, { stdio: 'pipe', cwd: ZIG_DIR });
  } catch (err: unknown) {
    const error = err as { stderr?: Buffer };
    console.error(`  FAILED to compile ${file}:`);
    console.error(error.stderr?.toString() ?? '');
    process.exit(1);
  }

  // Read .wasm binary
  const wasmBytes = readFileSync(wasmPath);
  const base64 = wasmBytes.toString('base64');

  // Parse exports from Zig source
  const zigSource = readFileSync(zigPath, 'utf-8');
  const exports = parseZigExports(zigSource);

  // Generate .wasm.ts and format with prettier
  const tsContent = generateWasmTs(name, base64, exports);
  const tsPath = join(BINS_DIR, `${name}.wasm.ts`);
  writeFileSync(tsPath, tsContent);
  execSync(`npx prettier --write "${tsPath}"`, { stdio: 'pipe' });

  console.log(
    `  ${name}.wasm.ts — ${wasmBytes.length} bytes WASM, ${exports.length} exports (${exports.map((e) => e.name).join(', ')})`
  );
}

// Clean up
rmSync(TMP_DIR, { recursive: true, force: true });

console.log(`\nWASM build complete.`);
