/**
 * WASM Build Script
 *
 * Compiles Zig kernels to .wasm, base64-encodes them, and generates
 * TypeScript wrapper modules in src/wasm/bins/.
 *
 * Usage: tsx scripts/build-wasm.ts
 *
 * Requires Zig installed. If Zig is not found, exits with a warning
 * (checked-in .wasm.ts files will be used as-is).
 */

import { execSync } from 'child_process';
import { readdirSync, readFileSync, writeFileSync, mkdirSync, rmSync } from 'fs';
import { join } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = join(__filename, '..');
const ROOT = join(__dirname, '..');

const ZIG_DIR = join(ROOT, 'src/wasm/zig');
const BINS_DIR = join(ROOT, 'src/wasm/bins');
const TMP_DIR = join(ROOT, '.wasm-tmp');

// --- Check for Zig ---

try {
  const version = execSync('zig version', { encoding: 'utf-8' }).trim();
  console.log(`Found Zig ${version}`);
} catch {
  console.warn('WARNING: Zig not found — skipping WASM build.');
  console.warn('Checked-in .wasm.ts files will be used. Install Zig to rebuild.');
  process.exit(0);
}

// --- Parse Zig exports ---

function parseZigExports(zigSource: string): { name: string; params: string }[] {
  const exports: { name: string; params: string }[] = [];
  const regex = /^export fn (\w+)\(([^)]*)\)\s*\w+/gm;
  let match;
  while ((match = regex.exec(zigSource)) !== null) {
    exports.push({ name: match[1]!, params: match[2]! });
  }
  return exports;
}

/**
 * Parse Zig function parameters into TypeScript parameter types.
 * All WASM numeric params become `number` in TypeScript.
 */
function zigParamsToTs(params: string): string {
  if (!params.trim()) return '';
  return params
    .split(',')
    .map((p) => {
      const name = p.trim().split(':')[0]!.trim();
      // Skip comptime params
      if (name.startsWith('comptime')) return null;
      return `${name}: number`;
    })
    .filter(Boolean)
    .join(', ');
}

// --- Generate .wasm.ts module ---

function generateWasmTs(
  kernelName: string,
  base64: string,
  exports: { name: string; params: string }[]
): string {
  const lines: string[] = [];

  lines.push(`// AUTO-GENERATED by build:wasm — do not edit. Regenerate with: npm run build:wasm`);
  lines.push(``);
  lines.push(`import { getSharedMemory, setHeapBase } from '../runtime';`);
  lines.push(``);
  lines.push(`const B64 = "${base64}";`);
  lines.push(``);
  lines.push(`let inst: WebAssembly.Instance | null = null;`);
  lines.push(``);
  lines.push(`function init(): WebAssembly.Instance {`);
  lines.push(`  if (inst) return inst;`);
  lines.push(`  const raw = atob(B64);`);
  lines.push(`  const bytes = new Uint8Array(raw.length);`);
  lines.push(`  for (let i = 0; i < raw.length; i++) bytes[i] = raw.charCodeAt(i);`);
  lines.push(`  inst = new WebAssembly.Instance(`);
  lines.push(`    new WebAssembly.Module(bytes),`);
  lines.push(`    { env: { memory: getSharedMemory() } }`);
  lines.push(`  );`);
  lines.push(`  // Register heap base so runtime knows where safe allocation starts`);
  lines.push(`  const heapBase = inst.exports['__heap_base'];`);
  lines.push(`  if (heapBase && typeof (heapBase as WebAssembly.Global).value === 'number') {`);
  lines.push(`    setHeapBase((heapBase as WebAssembly.Global).value as number);`);
  lines.push(`  }`);
  lines.push(`  return inst;`);
  lines.push(`}`);
  lines.push(``);

  for (const exp of exports) {
    const tsParams = zigParamsToTs(exp.params);
    lines.push(`export function ${exp.name}(${tsParams}): void {`);
    lines.push(`  const i = init();`);
    const argNames = tsParams
      ? tsParams
          .split(',')
          .map((p) => p.trim().split(':')[0]!.trim())
          .join(', ')
      : '';
    lines.push(`  (i.exports['${exp.name}'] as Function)(${argNames});`);
    lines.push(`}`);
    lines.push(``);
  }

  return lines.join('\n');
}

// --- Main build ---

mkdirSync(TMP_DIR, { recursive: true });
mkdirSync(BINS_DIR, { recursive: true });

const zigFiles = readdirSync(ZIG_DIR).filter(
  (f) => f.endsWith('.zig') && f !== 'simd.zig'
);

console.log(`Building ${zigFiles.length} WASM kernel(s)...\n`);

// --- Run Zig tests ---

console.log('Running Zig tests...\n');

for (const file of zigFiles) {
  const zigPath = join(ZIG_DIR, file);
  console.log(`  Testing ${file}...`);
  try {
    execSync(`zig test ${zigPath}`, { stdio: 'pipe', cwd: ZIG_DIR });
    console.log(`  ✓ ${file} — all tests passed`);
  } catch (err: unknown) {
    const error = err as { stderr?: Buffer; stdout?: Buffer };
    console.error(`  ✗ ${file} — tests FAILED:`);
    console.error(error.stderr?.toString() ?? error.stdout?.toString() ?? '');
    process.exit(1);
  }
}

console.log('');

// --- Compile to WASM ---

for (const file of zigFiles) {
  const name = file.replace('.zig', '');
  const zigPath = join(ZIG_DIR, file);
  const wasmPath = join(TMP_DIR, `${name}.wasm`);

  // Compile Zig -> .wasm
  console.log(`  Compiling ${file}...`);
  try {
    execSync(
      [
        'zig', 'build-exe',
        zigPath,
        '-target', 'wasm32-freestanding',
        '-O', 'ReleaseFast',
        '-mcpu=generic+simd128',
        '-fno-entry',
        '-rdynamic',
        '-fstrip',
        `--import-memory`,
        `-femit-bin=${wasmPath}`,
      ].join(' '),
      { stdio: 'pipe', cwd: ZIG_DIR }
    );
  } catch (err: unknown) {
    const error = err as { stderr?: Buffer };
    console.error(`  FAILED to compile ${file}:`);
    console.error(error.stderr?.toString() ?? '');
    process.exit(1);
  }

  // Read .wasm binary
  const wasmBytes = readFileSync(wasmPath);
  const base64 = wasmBytes.toString('base64');

  // Parse exports from Zig source
  const zigSource = readFileSync(zigPath, 'utf-8');
  const exports = parseZigExports(zigSource);

  // Generate .wasm.ts
  const tsContent = generateWasmTs(name, base64, exports);
  const tsPath = join(BINS_DIR, `${name}.wasm.ts`);
  writeFileSync(tsPath, tsContent);

  console.log(
    `  ${name}.wasm.ts — ${wasmBytes.length} bytes WASM, ${exports.length} exports (${exports.map((e) => e.name).join(', ')})`
  );
}

// Clean up
rmSync(TMP_DIR, { recursive: true, force: true });

console.log(`\nWASM build complete.`);
