/**
 * WASM Build Script
 *
 * Compiles Zig kernels to .wasm, base64-encodes them, and generates
 * TypeScript wrapper modules in src/common/wasm/bins/.
 *
 * Usage: tsx scripts/build-wasm.ts [--safe] [--force]
 *
 * Features:
 * - Per-mode caching: ReleaseFast and ReleaseSafe builds are cached independently
 *   in .wasm-cache/{fast,safe}/, so switching modes never causes a full rebuild.
 * - Content-based hashing: hash of kernel source + shared modules + zig version + flags.
 * - Parallel compilation: tests and builds run concurrently across all kernels.
 *
 * Requires Zig installed. If Zig is not found, exits with a warning
 * (checked-in .wasm.ts files will be used as-is).
 */

import { execSync, execFile } from 'child_process';
import {
  readdirSync,
  readFileSync,
  writeFileSync,
  mkdirSync,
  rmSync,
  existsSync,
  copyFileSync,
} from 'fs';
import { join } from 'path';
import { fileURLToPath } from 'url';
import { createHash } from 'crypto';
import { promisify } from 'util';

const execFileAsync = promisify(execFile);

const __filename = fileURLToPath(import.meta.url);
const __dirname = join(__filename, '..');
const ROOT = join(__dirname, '..');

const ZIG_DIR = join(ROOT, 'src/common/wasm/zig');
const BINS_DIR = join(ROOT, 'src/common/wasm/bins');
const TMP_DIR = join(ROOT, '.wasm-tmp');

// --safe flag: compile with ReleaseSafe (bounds checks, overflow detection)
const SAFE_MODE = process.argv.includes('--safe');
const FORCE_BUILD = process.argv.includes('--force');
const ZIG_OPT = SAFE_MODE ? 'ReleaseSafe' : 'ReleaseFast';
const MODE_KEY = SAFE_MODE ? 'safe' : 'fast';

// Per-mode cache directories
const CACHE_DIR = join(ROOT, '.wasm-cache', MODE_KEY);
const CACHE_HASHES_FILE = join(CACHE_DIR, 'hashes.json');

// --- Check for Zig ---

let zigVersion: string;
try {
  zigVersion = execSync('zig version', { encoding: 'utf-8' }).trim();
  console.log(`Found Zig ${zigVersion}`);
} catch {
  console.warn('WARNING: Zig not found — skipping WASM build.');
  console.warn('Checked-in .wasm.ts files will be used. Install Zig to rebuild.');
  process.exit(0);
}

// --- Cache ---

type Hashes = Record<string, string>;

function loadHashes(): Hashes {
  if (FORCE_BUILD) return {};
  try {
    return JSON.parse(readFileSync(CACHE_HASHES_FILE, 'utf-8')) as Hashes;
  } catch {
    return {};
  }
}

function saveHashes(hashes: Hashes): void {
  writeFileSync(CACHE_HASHES_FILE, JSON.stringify(hashes, null, 2) + '\n');
}

/**
 * Compute content hash for a kernel. Only includes shared modules that
 * the kernel actually imports (so changing sorting_common.zig doesn't
 * invalidate add.zig which only imports simd.zig).
 */
function computeHash(zigPath: string, sharedModuleSources: Map<string, string>): string {
  const h = createHash('sha256');
  const source = readFileSync(zigPath, 'utf-8');
  h.update(source);
  // Hash only the shared modules this kernel imports
  for (const [name, content] of sharedModuleSources) {
    if (source.includes(`@import("${name}")`)) {
      h.update(content);
    }
  }
  h.update(zigVersion);
  h.update(ZIG_OPT);
  return h.digest('hex');
}

// --- Parse Zig exports ---

function parseZigExports(
  zigSource: string
): { name: string; params: string; returnType: string }[] {
  const exports: { name: string; params: string; returnType: string }[] = [];
  const regex = /^export fn (\w+)\(([^)]*)\)\s*(\w+)/gm;
  let match;
  while ((match = regex.exec(zigSource)) !== null) {
    const zigRet = match[3]!;
    const returnType = zigRet === 'void' ? 'void' : 'number';
    exports.push({ name: match[1]!, params: match[2]!, returnType });
  }
  return exports;
}

/**
 * Parse Zig function parameters into TypeScript parameter types and detect i64/u64 params.
 */
function zigParamsToTs(params: string): { tsParams: string; bigintParams: Set<string> } {
  if (!params.trim()) return { tsParams: '', bigintParams: new Set() };
  const bigintParams = new Set<string>();
  const tsParams = params
    .split(',')
    .map((p) => {
      const parts = p.trim().split(':');
      const name = parts[0]!.trim();
      const zigType = parts.slice(1).join(':').trim();
      if (name.startsWith('comptime')) return null;
      if ((zigType === 'i64' || zigType === 'u64') && !zigType.includes('[*]')) {
        bigintParams.add(name);
      }
      return `${name}: number`;
    })
    .filter(Boolean)
    .join(', ');
  return { tsParams, bigintParams };
}

// --- Generate .wasm.ts module ---

function generateWasmTs(
  _kernelName: string,
  base64: string,
  exports: { name: string; params: string; returnType: string }[]
): string {
  const lines: string[] = [];

  lines.push(`// AUTO-GENERATED by build:wasm — do not edit. Regenerate with: npm run build:wasm`);
  lines.push(``);
  lines.push(`import { getSharedMemory, setHeapBase } from '../runtime';`);
  lines.push(``);
  lines.push(`const B64 =`);
  lines.push(`  '${base64}';`);
  lines.push(``);
  lines.push(`let inst: WebAssembly.Instance | null = null;`);
  lines.push(``);
  lines.push(`function init(): WebAssembly.Instance {`);
  lines.push(`  if (inst) return inst;`);
  lines.push(`  const raw = atob(B64);`);
  lines.push(`  const bytes = new Uint8Array(raw.length);`);
  lines.push(`  for (let i = 0; i < raw.length; i++) bytes[i] = raw.charCodeAt(i);`);
  lines.push(`  inst = new WebAssembly.Instance(new WebAssembly.Module(bytes), {`);
  lines.push(`    env: { memory: getSharedMemory() },`);
  lines.push(`  });`);
  lines.push(`  // Register heap base so runtime knows where safe allocation starts`);
  lines.push(`  const heapBase = inst.exports['__heap_base'];`);
  lines.push(`  if (heapBase && typeof (heapBase as WebAssembly.Global).value === 'number') {`);
  lines.push(`    setHeapBase((heapBase as WebAssembly.Global).value as number);`);
  lines.push(`  }`);
  lines.push(`  return inst;`);
  lines.push(`}`);
  lines.push(``);

  for (const exp of exports) {
    const { tsParams, bigintParams } = zigParamsToTs(exp.params);
    const ret = exp.returnType;
    const retPrefix = ret === 'void' ? '' : 'return ';
    lines.push(`export function ${exp.name}(${tsParams}): ${ret} {`);
    lines.push(`  const i = init();`);
    const argNames = tsParams
      ? tsParams
          .split(',')
          .map((p) => p.trim().split(':')[0]!.trim())
          .join(', ')
      : '';
    if (bigintParams.size > 0) {
      const castArgs = tsParams
        ? tsParams
            .split(',')
            .map((p) => {
              const name = p.trim().split(':')[0]!.trim();
              return bigintParams.has(name) ? `BigInt(Math.round(${name}))` : name;
            })
            .join(', ')
        : '';
      lines.push(
        `  ${retPrefix}(i.exports['${exp.name}'] as (...args: (number | bigint)[]) => ${ret})(${castArgs});`
      );
    } else {
      lines.push(
        `  ${retPrefix}(i.exports['${exp.name}'] as (...args: number[]) => ${ret})(${argNames});`
      );
    }
    lines.push(`}`);
    lines.push(``);
  }

  return lines.join('\n');
}

// --- Test a single kernel ---

async function testKernel(file: string): Promise<{ name: string; error?: string }> {
  const name = file.replace('.zig', '');
  const zigPath = join(ZIG_DIR, file);
  try {
    await execFileAsync('zig', ['test', zigPath], { cwd: ZIG_DIR });
    return { name };
  } catch (err: unknown) {
    const error = err as { stderr?: string; stdout?: string };
    return { name, error: `tests FAILED:\n${error.stderr ?? error.stdout ?? ''}` };
  }
}

// --- Compile a single kernel ---

async function compileKernel(
  file: string,
  sharedSources: Map<string, string>,
  hashes: Hashes
): Promise<{ name: string; skipped: boolean; error?: string }> {
  const name = file.replace('.zig', '');
  const zigPath = join(ZIG_DIR, file);
  const hash = computeHash(zigPath, sharedSources);
  const tsPath = join(BINS_DIR, `${name}.wasm.ts`);
  const cachePath = join(CACHE_DIR, `${name}.wasm.ts`);

  // Check if cached output is current
  if (hashes[name] === hash && existsSync(cachePath)) {
    // Just copy from cache to bins
    copyFileSync(cachePath, tsPath);
    return { name, skipped: true };
  }

  // Compile
  const wasmPath = join(TMP_DIR, `${name}.wasm`);
  const zigArgs = [
    'build-exe',
    zigPath,
    '-target',
    'wasm32-freestanding',
    '-O',
    ZIG_OPT,
    '-mcpu=generic+simd128',
    '-fno-entry',
    '-rdynamic',
    `--import-memory`,
    `-femit-bin=${wasmPath}`,
  ];
  if (!SAFE_MODE) zigArgs.push('-fstrip');

  try {
    await execFileAsync('zig', zigArgs, { cwd: ZIG_DIR });
  } catch (err: unknown) {
    const error = err as { stderr?: string };
    return { name, skipped: false, error: `compilation FAILED:\n${error.stderr ?? ''}` };
  }

  // Read .wasm binary
  const wasmBytes = readFileSync(wasmPath);
  const base64 = wasmBytes.toString('base64');

  // Parse exports from Zig source
  const zigSource = readFileSync(zigPath, 'utf-8');
  const exports = parseZigExports(zigSource);

  // Generate .wasm.ts
  const tsContent = generateWasmTs(name, base64, exports);

  // Write to bins/, format, then copy formatted version to cache
  writeFileSync(tsPath, tsContent);
  execSync(`npx prettier --write "${tsPath}"`, { stdio: 'pipe' });
  copyFileSync(tsPath, cachePath);

  // Update hash
  hashes[name] = hash;

  return { name, skipped: false };
}

// --- Main build ---

async function main() {
  mkdirSync(TMP_DIR, { recursive: true });
  mkdirSync(BINS_DIR, { recursive: true });
  mkdirSync(CACHE_DIR, { recursive: true });

  const SHARED_MODULES = new Set(['simd.zig', 'sorting_common.zig']);
  const zigFiles = readdirSync(ZIG_DIR).filter(
    (f) => f.endsWith('.zig') && !SHARED_MODULES.has(f)
  );

  const hashes = loadHashes();

  // Read shared module sources for hash computation
  const sharedSources = new Map<string, string>();
  for (const m of SHARED_MODULES) {
    const p = join(ZIG_DIR, m);
    if (existsSync(p)) sharedSources.set(m, readFileSync(p, 'utf-8'));
  }

  // Determine which kernels need recompilation
  const stale = zigFiles.filter((file) => {
    const name = file.replace('.zig', '');
    const hash = computeHash(join(ZIG_DIR, file), sharedSources);
    const cachePath = join(CACHE_DIR, `${name}.wasm.ts`);
    return !(hashes[name] === hash && existsSync(cachePath));
  });

  const cached = zigFiles.length - stale.length;

  if (stale.length === 0) {
    // All cached — just copy from cache to bins to ensure bins/ matches current mode
    let restored = 0;
    for (const file of zigFiles) {
      const name = file.replace('.zig', '');
      const cachePath = join(CACHE_DIR, `${name}.wasm.ts`);
      const tsPath = join(BINS_DIR, `${name}.wasm.ts`);
      if (existsSync(cachePath)) {
        copyFileSync(cachePath, tsPath);
        restored++;
      }
    }
    console.log(`All ${cached} kernel(s) cached — restored ${restored} to bins/ [${ZIG_OPT}]\n`);
    rmSync(TMP_DIR, { recursive: true, force: true });
    return;
  }

  console.log(`${stale.length} kernel(s) to build, ${cached} cached [${ZIG_OPT}]\n`);

  // Phase 1: Test all stale kernels in parallel
  console.log('Testing...\n');
  const testResults = await Promise.all(stale.map((file) => testKernel(file)));

  const testFailures = testResults.filter((r) => r.error);
  if (testFailures.length > 0) {
    for (const f of testFailures) {
      console.error(`  ✗ ${f.name} — ${f.error}`);
    }
    const passed = testResults.length - testFailures.length;
    console.error(`\n${testFailures.length} test failure(s), ${passed} passed. Build aborted.\n`);
    rmSync(TMP_DIR, { recursive: true, force: true });
    process.exit(1);
  }

  console.log(`  ${stale.length} test(s) passed.\n`);

  // Phase 2: Compile stale kernels + copy cached kernels, all in parallel
  console.log('Compiling...\n');
  const buildResults = await Promise.all(
    zigFiles.map((file) => compileKernel(file, sharedSources, hashes))
  );

  // Report results
  let failed = false;
  let built = 0;
  let restored = 0;
  for (const result of buildResults) {
    if (result.error) {
      console.error(`  ✗ ${result.name} — ${result.error}`);
      failed = true;
    } else if (result.skipped) {
      restored++;
    } else {
      console.log(`  ✓ ${result.name}`);
      built++;
    }
  }

  if (failed) {
    rmSync(TMP_DIR, { recursive: true, force: true });
    process.exit(1);
  }

  // Save hashes
  saveHashes(hashes);

  // Clean up
  rmSync(TMP_DIR, { recursive: true, force: true });

  // Delete old single-file cache if it exists
  const oldCacheFile = join(ROOT, '.wasm-cache.json');
  if (existsSync(oldCacheFile)) rmSync(oldCacheFile);

  console.log(
    `\nWASM build complete: ${built} built, ${restored} from cache [${ZIG_OPT}]`
  );
}

main();
